// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: components/workflow/transport/grpc/proto/workflow.proto

package workflowpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowService_CreateDefinition_FullMethodName            = "/gaia.workflow.v1.WorkflowService/CreateDefinition"
	WorkflowService_UpdateDefinition_FullMethodName            = "/gaia.workflow.v1.WorkflowService/UpdateDefinition"
	WorkflowService_DeployDefinition_FullMethodName            = "/gaia.workflow.v1.WorkflowService/DeployDefinition"
	WorkflowService_GetDefinition_FullMethodName               = "/gaia.workflow.v1.WorkflowService/GetDefinition"
	WorkflowService_ListDefinitions_FullMethodName             = "/gaia.workflow.v1.WorkflowService/ListDefinitions"
	WorkflowService_DisableDefinition_FullMethodName           = "/gaia.workflow.v1.WorkflowService/DisableDefinition"
	WorkflowService_EnableDefinition_FullMethodName            = "/gaia.workflow.v1.WorkflowService/EnableDefinition"
	WorkflowService_StartProcess_FullMethodName                = "/gaia.workflow.v1.WorkflowService/StartProcess"
	WorkflowService_GetInstance_FullMethodName                 = "/gaia.workflow.v1.WorkflowService/GetInstance"
	WorkflowService_ListInstances_FullMethodName               = "/gaia.workflow.v1.WorkflowService/ListInstances"
	WorkflowService_TerminateInstance_FullMethodName           = "/gaia.workflow.v1.WorkflowService/TerminateInstance"
	WorkflowService_SuspendInstance_FullMethodName             = "/gaia.workflow.v1.WorkflowService/SuspendInstance"
	WorkflowService_ResumeInstance_FullMethodName              = "/gaia.workflow.v1.WorkflowService/ResumeInstance"
	WorkflowService_ListTasks_FullMethodName                   = "/gaia.workflow.v1.WorkflowService/ListTasks"
	WorkflowService_InstanceTasks_FullMethodName               = "/gaia.workflow.v1.WorkflowService/InstanceTasks"
	WorkflowService_Variables_FullMethodName                   = "/gaia.workflow.v1.WorkflowService/Variables"
	WorkflowService_VariablesByNames_FullMethodName            = "/gaia.workflow.v1.WorkflowService/VariablesByNames"
	WorkflowService_UpdateVariables_FullMethodName             = "/gaia.workflow.v1.WorkflowService/UpdateVariables"
	WorkflowService_DeleteVariables_FullMethodName             = "/gaia.workflow.v1.WorkflowService/DeleteVariables"
	WorkflowService_SystemVariables_FullMethodName             = "/gaia.workflow.v1.WorkflowService/SystemVariables"
	WorkflowService_Timeline_FullMethodName                    = "/gaia.workflow.v1.WorkflowService/Timeline"
	WorkflowService_CompleteTask_FullMethodName                = "/gaia.workflow.v1.WorkflowService/CompleteTask"
	WorkflowService_FailTask_FullMethodName                    = "/gaia.workflow.v1.WorkflowService/FailTask"
	WorkflowService_RetryTask_FullMethodName                   = "/gaia.workflow.v1.WorkflowService/RetryTask"
	WorkflowService_ClaimTask_FullMethodName                   = "/gaia.workflow.v1.WorkflowService/ClaimTask"
	WorkflowService_UnclaimTask_FullMethodName                 = "/gaia.workflow.v1.WorkflowService/UnclaimTask"
	WorkflowService_TransferTask_FullMethodName                = "/gaia.workflow.v1.WorkflowService/TransferTask"
	WorkflowService_DelegateTask_FullMethodName                = "/gaia.workflow.v1.WorkflowService/DelegateTask"
	WorkflowService_RejectTask_FullMethodName                  = "/gaia.workflow.v1.WorkflowService/RejectTask"
	WorkflowService_ScanTimeoutTasks_FullMethodName            = "/gaia.workflow.v1.WorkflowService/ScanTimeoutTasks"
	WorkflowService_Outbox_FullMethodName                      = "/gaia.workflow.v1.WorkflowService/Outbox"
	WorkflowService_PurgeOutbox_FullMethodName                 = "/gaia.workflow.v1.WorkflowService/PurgeOutbox"
	WorkflowService_RegisterAutomationService_FullMethodName   = "/gaia.workflow.v1.WorkflowService/RegisterAutomationService"
	WorkflowService_UnregisterAutomationService_FullMethodName = "/gaia.workflow.v1.WorkflowService/UnregisterAutomationService"
	WorkflowService_ListAutomationServices_FullMethodName      = "/gaia.workflow.v1.WorkflowService/ListAutomationServices"
	WorkflowService_ListAutomationTasks_FullMethodName         = "/gaia.workflow.v1.WorkflowService/ListAutomationTasks"
)

// WorkflowServiceClient is the client API for WorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowServiceClient interface {
	CreateDefinition(ctx context.Context, in *ProcessDefinitionRequest, opts ...grpc.CallOption) (*ProcessDefinition, error)
	UpdateDefinition(ctx context.Context, in *UpdateDefinitionRequest, opts ...grpc.CallOption) (*ProcessDefinition, error)
	DeployDefinition(ctx context.Context, in *ProcessDefinition, opts ...grpc.CallOption) (*ProcessDefinition, error)
	GetDefinition(ctx context.Context, in *GetDefinitionRequest, opts ...grpc.CallOption) (*ProcessDefinition, error)
	ListDefinitions(ctx context.Context, in *ListDefinitionsRequest, opts ...grpc.CallOption) (*ProcessDefinitionPage, error)
	DisableDefinition(ctx context.Context, in *GetDefinitionRequest, opts ...grpc.CallOption) (*ProcessDefinition, error)
	EnableDefinition(ctx context.Context, in *GetDefinitionRequest, opts ...grpc.CallOption) (*ProcessDefinition, error)
	StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*ProcessInstance, error)
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*ProcessInstance, error)
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ProcessInstancePage, error)
	TerminateInstance(ctx context.Context, in *InstanceLifecycleRequest, opts ...grpc.CallOption) (*ProcessInstance, error)
	SuspendInstance(ctx context.Context, in *InstanceLifecycleRequest, opts ...grpc.CallOption) (*ProcessInstance, error)
	ResumeInstance(ctx context.Context, in *InstanceLifecycleRequest, opts ...grpc.CallOption) (*ProcessInstance, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*TaskPage, error)
	InstanceTasks(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*TaskList, error)
	Variables(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*VariablesResponse, error)
	VariablesByNames(ctx context.Context, in *VariableNamesRequest, opts ...grpc.CallOption) (*VariablesResponse, error)
	UpdateVariables(ctx context.Context, in *UpdateVariablesRequest, opts ...grpc.CallOption) (*VariablesResponse, error)
	DeleteVariables(ctx context.Context, in *VariableNamesRequest, opts ...grpc.CallOption) (*VariablesResponse, error)
	SystemVariables(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*InstanceSystemVariables, error)
	Timeline(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*AuditEventList, error)
	CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*ProcessInstance, error)
	FailTask(ctx context.Context, in *FailTaskRequest, opts ...grpc.CallOption) (*ProcessInstance, error)
	RetryTask(ctx context.Context, in *RetryTaskRequest, opts ...grpc.CallOption) (*Task, error)
	ClaimTask(ctx context.Context, in *TaskOperationRequest, opts ...grpc.CallOption) (*Task, error)
	UnclaimTask(ctx context.Context, in *TaskOperationRequest, opts ...grpc.CallOption) (*Task, error)
	TransferTask(ctx context.Context, in *TaskOperationRequest, opts ...grpc.CallOption) (*Task, error)
	DelegateTask(ctx context.Context, in *TaskOperationRequest, opts ...grpc.CallOption) (*Task, error)
	RejectTask(ctx context.Context, in *TaskOperationRequest, opts ...grpc.CallOption) (*ProcessInstance, error)
	ScanTimeoutTasks(ctx context.Context, in *ScanTimeoutTasksRequest, opts ...grpc.CallOption) (*ScanTimeoutTasksResult, error)
	Outbox(ctx context.Context, in *OutboxRequest, opts ...grpc.CallOption) (*OutboxEventPage, error)
	PurgeOutbox(ctx context.Context, in *PurgeOutboxRequest, opts ...grpc.CallOption) (*PurgeOutboxResponse, error)
	RegisterAutomationService(ctx context.Context, in *AutomationService, opts ...grpc.CallOption) (*AutomationService, error)
	UnregisterAutomationService(ctx context.Context, in *AutomationServiceID, opts ...grpc.CallOption) (*DeleteResponse, error)
	ListAutomationServices(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*AutomationServiceList, error)
	ListAutomationTasks(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*AutomationTaskList, error)
}

type workflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowServiceClient(cc grpc.ClientConnInterface) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) CreateDefinition(ctx context.Context, in *ProcessDefinitionRequest, opts ...grpc.CallOption) (*ProcessDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessDefinition)
	err := c.cc.Invoke(ctx, WorkflowService_CreateDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) UpdateDefinition(ctx context.Context, in *UpdateDefinitionRequest, opts ...grpc.CallOption) (*ProcessDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessDefinition)
	err := c.cc.Invoke(ctx, WorkflowService_UpdateDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DeployDefinition(ctx context.Context, in *ProcessDefinition, opts ...grpc.CallOption) (*ProcessDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessDefinition)
	err := c.cc.Invoke(ctx, WorkflowService_DeployDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetDefinition(ctx context.Context, in *GetDefinitionRequest, opts ...grpc.CallOption) (*ProcessDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessDefinition)
	err := c.cc.Invoke(ctx, WorkflowService_GetDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListDefinitions(ctx context.Context, in *ListDefinitionsRequest, opts ...grpc.CallOption) (*ProcessDefinitionPage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessDefinitionPage)
	err := c.cc.Invoke(ctx, WorkflowService_ListDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DisableDefinition(ctx context.Context, in *GetDefinitionRequest, opts ...grpc.CallOption) (*ProcessDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessDefinition)
	err := c.cc.Invoke(ctx, WorkflowService_DisableDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) EnableDefinition(ctx context.Context, in *GetDefinitionRequest, opts ...grpc.CallOption) (*ProcessDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessDefinition)
	err := c.cc.Invoke(ctx, WorkflowService_EnableDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*ProcessInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessInstance)
	err := c.cc.Invoke(ctx, WorkflowService_StartProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*ProcessInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessInstance)
	err := c.cc.Invoke(ctx, WorkflowService_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ProcessInstancePage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessInstancePage)
	err := c.cc.Invoke(ctx, WorkflowService_ListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) TerminateInstance(ctx context.Context, in *InstanceLifecycleRequest, opts ...grpc.CallOption) (*ProcessInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessInstance)
	err := c.cc.Invoke(ctx, WorkflowService_TerminateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) SuspendInstance(ctx context.Context, in *InstanceLifecycleRequest, opts ...grpc.CallOption) (*ProcessInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessInstance)
	err := c.cc.Invoke(ctx, WorkflowService_SuspendInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ResumeInstance(ctx context.Context, in *InstanceLifecycleRequest, opts ...grpc.CallOption) (*ProcessInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessInstance)
	err := c.cc.Invoke(ctx, WorkflowService_ResumeInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*TaskPage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskPage)
	err := c.cc.Invoke(ctx, WorkflowService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) InstanceTasks(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*TaskList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskList)
	err := c.cc.Invoke(ctx, WorkflowService_InstanceTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) Variables(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*VariablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariablesResponse)
	err := c.cc.Invoke(ctx, WorkflowService_Variables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) VariablesByNames(ctx context.Context, in *VariableNamesRequest, opts ...grpc.CallOption) (*VariablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariablesResponse)
	err := c.cc.Invoke(ctx, WorkflowService_VariablesByNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) UpdateVariables(ctx context.Context, in *UpdateVariablesRequest, opts ...grpc.CallOption) (*VariablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariablesResponse)
	err := c.cc.Invoke(ctx, WorkflowService_UpdateVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DeleteVariables(ctx context.Context, in *VariableNamesRequest, opts ...grpc.CallOption) (*VariablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariablesResponse)
	err := c.cc.Invoke(ctx, WorkflowService_DeleteVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) SystemVariables(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*InstanceSystemVariables, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceSystemVariables)
	err := c.cc.Invoke(ctx, WorkflowService_SystemVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) Timeline(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*AuditEventList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditEventList)
	err := c.cc.Invoke(ctx, WorkflowService_Timeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*ProcessInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessInstance)
	err := c.cc.Invoke(ctx, WorkflowService_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) FailTask(ctx context.Context, in *FailTaskRequest, opts ...grpc.CallOption) (*ProcessInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessInstance)
	err := c.cc.Invoke(ctx, WorkflowService_FailTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) RetryTask(ctx context.Context, in *RetryTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, WorkflowService_RetryTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ClaimTask(ctx context.Context, in *TaskOperationRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, WorkflowService_ClaimTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) UnclaimTask(ctx context.Context, in *TaskOperationRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, WorkflowService_UnclaimTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) TransferTask(ctx context.Context, in *TaskOperationRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, WorkflowService_TransferTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DelegateTask(ctx context.Context, in *TaskOperationRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, WorkflowService_DelegateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) RejectTask(ctx context.Context, in *TaskOperationRequest, opts ...grpc.CallOption) (*ProcessInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessInstance)
	err := c.cc.Invoke(ctx, WorkflowService_RejectTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ScanTimeoutTasks(ctx context.Context, in *ScanTimeoutTasksRequest, opts ...grpc.CallOption) (*ScanTimeoutTasksResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanTimeoutTasksResult)
	err := c.cc.Invoke(ctx, WorkflowService_ScanTimeoutTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) Outbox(ctx context.Context, in *OutboxRequest, opts ...grpc.CallOption) (*OutboxEventPage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutboxEventPage)
	err := c.cc.Invoke(ctx, WorkflowService_Outbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) PurgeOutbox(ctx context.Context, in *PurgeOutboxRequest, opts ...grpc.CallOption) (*PurgeOutboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeOutboxResponse)
	err := c.cc.Invoke(ctx, WorkflowService_PurgeOutbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) RegisterAutomationService(ctx context.Context, in *AutomationService, opts ...grpc.CallOption) (*AutomationService, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutomationService)
	err := c.cc.Invoke(ctx, WorkflowService_RegisterAutomationService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) UnregisterAutomationService(ctx context.Context, in *AutomationServiceID, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, WorkflowService_UnregisterAutomationService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListAutomationServices(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*AutomationServiceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutomationServiceList)
	err := c.cc.Invoke(ctx, WorkflowService_ListAutomationServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListAutomationTasks(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*AutomationTaskList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutomationTaskList)
	err := c.cc.Invoke(ctx, WorkflowService_ListAutomationTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServiceServer is the server API for WorkflowService service.
// All implementations must embed UnimplementedWorkflowServiceServer
// for forward compatibility.
type WorkflowServiceServer interface {
	CreateDefinition(context.Context, *ProcessDefinitionRequest) (*ProcessDefinition, error)
	UpdateDefinition(context.Context, *UpdateDefinitionRequest) (*ProcessDefinition, error)
	DeployDefinition(context.Context, *ProcessDefinition) (*ProcessDefinition, error)
	GetDefinition(context.Context, *GetDefinitionRequest) (*ProcessDefinition, error)
	ListDefinitions(context.Context, *ListDefinitionsRequest) (*ProcessDefinitionPage, error)
	DisableDefinition(context.Context, *GetDefinitionRequest) (*ProcessDefinition, error)
	EnableDefinition(context.Context, *GetDefinitionRequest) (*ProcessDefinition, error)
	StartProcess(context.Context, *StartProcessRequest) (*ProcessInstance, error)
	GetInstance(context.Context, *GetInstanceRequest) (*ProcessInstance, error)
	ListInstances(context.Context, *ListInstancesRequest) (*ProcessInstancePage, error)
	TerminateInstance(context.Context, *InstanceLifecycleRequest) (*ProcessInstance, error)
	SuspendInstance(context.Context, *InstanceLifecycleRequest) (*ProcessInstance, error)
	ResumeInstance(context.Context, *InstanceLifecycleRequest) (*ProcessInstance, error)
	ListTasks(context.Context, *ListTasksRequest) (*TaskPage, error)
	InstanceTasks(context.Context, *GetInstanceRequest) (*TaskList, error)
	Variables(context.Context, *GetInstanceRequest) (*VariablesResponse, error)
	VariablesByNames(context.Context, *VariableNamesRequest) (*VariablesResponse, error)
	UpdateVariables(context.Context, *UpdateVariablesRequest) (*VariablesResponse, error)
	DeleteVariables(context.Context, *VariableNamesRequest) (*VariablesResponse, error)
	SystemVariables(context.Context, *GetInstanceRequest) (*InstanceSystemVariables, error)
	Timeline(context.Context, *GetInstanceRequest) (*AuditEventList, error)
	CompleteTask(context.Context, *CompleteTaskRequest) (*ProcessInstance, error)
	FailTask(context.Context, *FailTaskRequest) (*ProcessInstance, error)
	RetryTask(context.Context, *RetryTaskRequest) (*Task, error)
	ClaimTask(context.Context, *TaskOperationRequest) (*Task, error)
	UnclaimTask(context.Context, *TaskOperationRequest) (*Task, error)
	TransferTask(context.Context, *TaskOperationRequest) (*Task, error)
	DelegateTask(context.Context, *TaskOperationRequest) (*Task, error)
	RejectTask(context.Context, *TaskOperationRequest) (*ProcessInstance, error)
	ScanTimeoutTasks(context.Context, *ScanTimeoutTasksRequest) (*ScanTimeoutTasksResult, error)
	Outbox(context.Context, *OutboxRequest) (*OutboxEventPage, error)
	PurgeOutbox(context.Context, *PurgeOutboxRequest) (*PurgeOutboxResponse, error)
	RegisterAutomationService(context.Context, *AutomationService) (*AutomationService, error)
	UnregisterAutomationService(context.Context, *AutomationServiceID) (*DeleteResponse, error)
	ListAutomationServices(context.Context, *EmptyRequest) (*AutomationServiceList, error)
	ListAutomationTasks(context.Context, *EmptyRequest) (*AutomationTaskList, error)
	mustEmbedUnimplementedWorkflowServiceServer()
}

// UnimplementedWorkflowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowServiceServer struct{}

func (UnimplementedWorkflowServiceServer) CreateDefinition(context.Context, *ProcessDefinitionRequest) (*ProcessDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDefinition not implemented")
}
func (UnimplementedWorkflowServiceServer) UpdateDefinition(context.Context, *UpdateDefinitionRequest) (*ProcessDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDefinition not implemented")
}
func (UnimplementedWorkflowServiceServer) DeployDefinition(context.Context, *ProcessDefinition) (*ProcessDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployDefinition not implemented")
}
func (UnimplementedWorkflowServiceServer) GetDefinition(context.Context, *GetDefinitionRequest) (*ProcessDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefinition not implemented")
}
func (UnimplementedWorkflowServiceServer) ListDefinitions(context.Context, *ListDefinitionsRequest) (*ProcessDefinitionPage, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDefinitions not implemented")
}
func (UnimplementedWorkflowServiceServer) DisableDefinition(context.Context, *GetDefinitionRequest) (*ProcessDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableDefinition not implemented")
}
func (UnimplementedWorkflowServiceServer) EnableDefinition(context.Context, *GetDefinitionRequest) (*ProcessDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableDefinition not implemented")
}
func (UnimplementedWorkflowServiceServer) StartProcess(context.Context, *StartProcessRequest) (*ProcessInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method StartProcess not implemented")
}
func (UnimplementedWorkflowServiceServer) GetInstance(context.Context, *GetInstanceRequest) (*ProcessInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedWorkflowServiceServer) ListInstances(context.Context, *ListInstancesRequest) (*ProcessInstancePage, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedWorkflowServiceServer) TerminateInstance(context.Context, *InstanceLifecycleRequest) (*ProcessInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateInstance not implemented")
}
func (UnimplementedWorkflowServiceServer) SuspendInstance(context.Context, *InstanceLifecycleRequest) (*ProcessInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendInstance not implemented")
}
func (UnimplementedWorkflowServiceServer) ResumeInstance(context.Context, *InstanceLifecycleRequest) (*ProcessInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeInstance not implemented")
}
func (UnimplementedWorkflowServiceServer) ListTasks(context.Context, *ListTasksRequest) (*TaskPage, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedWorkflowServiceServer) InstanceTasks(context.Context, *GetInstanceRequest) (*TaskList, error) {
	return nil, status.Error(codes.Unimplemented, "method InstanceTasks not implemented")
}
func (UnimplementedWorkflowServiceServer) Variables(context.Context, *GetInstanceRequest) (*VariablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Variables not implemented")
}
func (UnimplementedWorkflowServiceServer) VariablesByNames(context.Context, *VariableNamesRequest) (*VariablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VariablesByNames not implemented")
}
func (UnimplementedWorkflowServiceServer) UpdateVariables(context.Context, *UpdateVariablesRequest) (*VariablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVariables not implemented")
}
func (UnimplementedWorkflowServiceServer) DeleteVariables(context.Context, *VariableNamesRequest) (*VariablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVariables not implemented")
}
func (UnimplementedWorkflowServiceServer) SystemVariables(context.Context, *GetInstanceRequest) (*InstanceSystemVariables, error) {
	return nil, status.Error(codes.Unimplemented, "method SystemVariables not implemented")
}
func (UnimplementedWorkflowServiceServer) Timeline(context.Context, *GetInstanceRequest) (*AuditEventList, error) {
	return nil, status.Error(codes.Unimplemented, "method Timeline not implemented")
}
func (UnimplementedWorkflowServiceServer) CompleteTask(context.Context, *CompleteTaskRequest) (*ProcessInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedWorkflowServiceServer) FailTask(context.Context, *FailTaskRequest) (*ProcessInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method FailTask not implemented")
}
func (UnimplementedWorkflowServiceServer) RetryTask(context.Context, *RetryTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryTask not implemented")
}
func (UnimplementedWorkflowServiceServer) ClaimTask(context.Context, *TaskOperationRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimTask not implemented")
}
func (UnimplementedWorkflowServiceServer) UnclaimTask(context.Context, *TaskOperationRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method UnclaimTask not implemented")
}
func (UnimplementedWorkflowServiceServer) TransferTask(context.Context, *TaskOperationRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferTask not implemented")
}
func (UnimplementedWorkflowServiceServer) DelegateTask(context.Context, *TaskOperationRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method DelegateTask not implemented")
}
func (UnimplementedWorkflowServiceServer) RejectTask(context.Context, *TaskOperationRequest) (*ProcessInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectTask not implemented")
}
func (UnimplementedWorkflowServiceServer) ScanTimeoutTasks(context.Context, *ScanTimeoutTasksRequest) (*ScanTimeoutTasksResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanTimeoutTasks not implemented")
}
func (UnimplementedWorkflowServiceServer) Outbox(context.Context, *OutboxRequest) (*OutboxEventPage, error) {
	return nil, status.Error(codes.Unimplemented, "method Outbox not implemented")
}
func (UnimplementedWorkflowServiceServer) PurgeOutbox(context.Context, *PurgeOutboxRequest) (*PurgeOutboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeOutbox not implemented")
}
func (UnimplementedWorkflowServiceServer) RegisterAutomationService(context.Context, *AutomationService) (*AutomationService, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAutomationService not implemented")
}
func (UnimplementedWorkflowServiceServer) UnregisterAutomationService(context.Context, *AutomationServiceID) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterAutomationService not implemented")
}
func (UnimplementedWorkflowServiceServer) ListAutomationServices(context.Context, *EmptyRequest) (*AutomationServiceList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAutomationServices not implemented")
}
func (UnimplementedWorkflowServiceServer) ListAutomationTasks(context.Context, *EmptyRequest) (*AutomationTaskList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAutomationTasks not implemented")
}
func (UnimplementedWorkflowServiceServer) mustEmbedUnimplementedWorkflowServiceServer() {}
func (UnimplementedWorkflowServiceServer) testEmbeddedByValue()                         {}

// UnsafeWorkflowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowServiceServer will
// result in compilation errors.
type UnsafeWorkflowServiceServer interface {
	mustEmbedUnimplementedWorkflowServiceServer()
}

func RegisterWorkflowServiceServer(s grpc.ServiceRegistrar, srv WorkflowServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkflowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowService_ServiceDesc, srv)
}

func _WorkflowService_CreateDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CreateDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_CreateDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CreateDefinition(ctx, req.(*ProcessDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_UpdateDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).UpdateDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_UpdateDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).UpdateDefinition(ctx, req.(*UpdateDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DeployDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessDefinition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DeployDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_DeployDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DeployDefinition(ctx, req.(*ProcessDefinition))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetDefinition(ctx, req.(*GetDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListDefinitions(ctx, req.(*ListDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DisableDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DisableDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_DisableDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DisableDefinition(ctx, req.(*GetDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_EnableDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).EnableDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_EnableDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).EnableDefinition(ctx, req.(*GetDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_StartProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).StartProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_StartProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).StartProcess(ctx, req.(*StartProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_TerminateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).TerminateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_TerminateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).TerminateInstance(ctx, req.(*InstanceLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_SuspendInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).SuspendInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_SuspendInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).SuspendInstance(ctx, req.(*InstanceLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ResumeInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ResumeInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ResumeInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ResumeInstance(ctx, req.(*InstanceLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_InstanceTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).InstanceTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_InstanceTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).InstanceTasks(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_Variables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).Variables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_Variables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).Variables(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_VariablesByNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VariableNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).VariablesByNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_VariablesByNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).VariablesByNames(ctx, req.(*VariableNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_UpdateVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).UpdateVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_UpdateVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).UpdateVariables(ctx, req.(*UpdateVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DeleteVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VariableNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DeleteVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_DeleteVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DeleteVariables(ctx, req.(*VariableNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_SystemVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).SystemVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_SystemVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).SystemVariables(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_Timeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).Timeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_Timeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).Timeline(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CompleteTask(ctx, req.(*CompleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_FailTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).FailTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_FailTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).FailTask(ctx, req.(*FailTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_RetryTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RetryTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_RetryTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RetryTask(ctx, req.(*RetryTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ClaimTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ClaimTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ClaimTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ClaimTask(ctx, req.(*TaskOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_UnclaimTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).UnclaimTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_UnclaimTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).UnclaimTask(ctx, req.(*TaskOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_TransferTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).TransferTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_TransferTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).TransferTask(ctx, req.(*TaskOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DelegateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DelegateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_DelegateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DelegateTask(ctx, req.(*TaskOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_RejectTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RejectTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_RejectTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RejectTask(ctx, req.(*TaskOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ScanTimeoutTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanTimeoutTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ScanTimeoutTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ScanTimeoutTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ScanTimeoutTasks(ctx, req.(*ScanTimeoutTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_Outbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).Outbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_Outbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).Outbox(ctx, req.(*OutboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_PurgeOutbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeOutboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).PurgeOutbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_PurgeOutbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).PurgeOutbox(ctx, req.(*PurgeOutboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_RegisterAutomationService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutomationService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RegisterAutomationService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_RegisterAutomationService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RegisterAutomationService(ctx, req.(*AutomationService))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_UnregisterAutomationService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutomationServiceID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).UnregisterAutomationService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_UnregisterAutomationService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).UnregisterAutomationService(ctx, req.(*AutomationServiceID))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListAutomationServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListAutomationServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListAutomationServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListAutomationServices(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListAutomationTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListAutomationTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListAutomationTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListAutomationTasks(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowService_ServiceDesc is the grpc.ServiceDesc for WorkflowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gaia.workflow.v1.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDefinition",
			Handler:    _WorkflowService_CreateDefinition_Handler,
		},
		{
			MethodName: "UpdateDefinition",
			Handler:    _WorkflowService_UpdateDefinition_Handler,
		},
		{
			MethodName: "DeployDefinition",
			Handler:    _WorkflowService_DeployDefinition_Handler,
		},
		{
			MethodName: "GetDefinition",
			Handler:    _WorkflowService_GetDefinition_Handler,
		},
		{
			MethodName: "ListDefinitions",
			Handler:    _WorkflowService_ListDefinitions_Handler,
		},
		{
			MethodName: "DisableDefinition",
			Handler:    _WorkflowService_DisableDefinition_Handler,
		},
		{
			MethodName: "EnableDefinition",
			Handler:    _WorkflowService_EnableDefinition_Handler,
		},
		{
			MethodName: "StartProcess",
			Handler:    _WorkflowService_StartProcess_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _WorkflowService_GetInstance_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _WorkflowService_ListInstances_Handler,
		},
		{
			MethodName: "TerminateInstance",
			Handler:    _WorkflowService_TerminateInstance_Handler,
		},
		{
			MethodName: "SuspendInstance",
			Handler:    _WorkflowService_SuspendInstance_Handler,
		},
		{
			MethodName: "ResumeInstance",
			Handler:    _WorkflowService_ResumeInstance_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _WorkflowService_ListTasks_Handler,
		},
		{
			MethodName: "InstanceTasks",
			Handler:    _WorkflowService_InstanceTasks_Handler,
		},
		{
			MethodName: "Variables",
			Handler:    _WorkflowService_Variables_Handler,
		},
		{
			MethodName: "VariablesByNames",
			Handler:    _WorkflowService_VariablesByNames_Handler,
		},
		{
			MethodName: "UpdateVariables",
			Handler:    _WorkflowService_UpdateVariables_Handler,
		},
		{
			MethodName: "DeleteVariables",
			Handler:    _WorkflowService_DeleteVariables_Handler,
		},
		{
			MethodName: "SystemVariables",
			Handler:    _WorkflowService_SystemVariables_Handler,
		},
		{
			MethodName: "Timeline",
			Handler:    _WorkflowService_Timeline_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _WorkflowService_CompleteTask_Handler,
		},
		{
			MethodName: "FailTask",
			Handler:    _WorkflowService_FailTask_Handler,
		},
		{
			MethodName: "RetryTask",
			Handler:    _WorkflowService_RetryTask_Handler,
		},
		{
			MethodName: "ClaimTask",
			Handler:    _WorkflowService_ClaimTask_Handler,
		},
		{
			MethodName: "UnclaimTask",
			Handler:    _WorkflowService_UnclaimTask_Handler,
		},
		{
			MethodName: "TransferTask",
			Handler:    _WorkflowService_TransferTask_Handler,
		},
		{
			MethodName: "DelegateTask",
			Handler:    _WorkflowService_DelegateTask_Handler,
		},
		{
			MethodName: "RejectTask",
			Handler:    _WorkflowService_RejectTask_Handler,
		},
		{
			MethodName: "ScanTimeoutTasks",
			Handler:    _WorkflowService_ScanTimeoutTasks_Handler,
		},
		{
			MethodName: "Outbox",
			Handler:    _WorkflowService_Outbox_Handler,
		},
		{
			MethodName: "PurgeOutbox",
			Handler:    _WorkflowService_PurgeOutbox_Handler,
		},
		{
			MethodName: "RegisterAutomationService",
			Handler:    _WorkflowService_RegisterAutomationService_Handler,
		},
		{
			MethodName: "UnregisterAutomationService",
			Handler:    _WorkflowService_UnregisterAutomationService_Handler,
		},
		{
			MethodName: "ListAutomationServices",
			Handler:    _WorkflowService_ListAutomationServices_Handler,
		},
		{
			MethodName: "ListAutomationTasks",
			Handler:    _WorkflowService_ListAutomationTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "components/workflow/transport/grpc/proto/workflow.proto",
}

const (
	AutomationWorkerService_DispatchTask_FullMethodName = "/gaia.workflow.v1.AutomationWorkerService/DispatchTask"
	AutomationWorkerService_Health_FullMethodName       = "/gaia.workflow.v1.AutomationWorkerService/Health"
)

// AutomationWorkerServiceClient is the client API for AutomationWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutomationWorkerServiceClient interface {
	DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error)
	Health(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type automationWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutomationWorkerServiceClient(cc grpc.ClientConnInterface) AutomationWorkerServiceClient {
	return &automationWorkerServiceClient{cc}
}

func (c *automationWorkerServiceClient) DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchTaskResponse)
	err := c.cc.Invoke(ctx, AutomationWorkerService_DispatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationWorkerServiceClient) Health(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AutomationWorkerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutomationWorkerServiceServer is the server API for AutomationWorkerService service.
// All implementations must embed UnimplementedAutomationWorkerServiceServer
// for forward compatibility.
type AutomationWorkerServiceServer interface {
	DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error)
	Health(context.Context, *EmptyRequest) (*HealthResponse, error)
	mustEmbedUnimplementedAutomationWorkerServiceServer()
}

// UnimplementedAutomationWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutomationWorkerServiceServer struct{}

func (UnimplementedAutomationWorkerServiceServer) DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchTask not implemented")
}
func (UnimplementedAutomationWorkerServiceServer) Health(context.Context, *EmptyRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAutomationWorkerServiceServer) mustEmbedUnimplementedAutomationWorkerServiceServer() {
}
func (UnimplementedAutomationWorkerServiceServer) testEmbeddedByValue() {}

// UnsafeAutomationWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutomationWorkerServiceServer will
// result in compilation errors.
type UnsafeAutomationWorkerServiceServer interface {
	mustEmbedUnimplementedAutomationWorkerServiceServer()
}

func RegisterAutomationWorkerServiceServer(s grpc.ServiceRegistrar, srv AutomationWorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedAutomationWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutomationWorkerService_ServiceDesc, srv)
}

func _AutomationWorkerService_DispatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationWorkerServiceServer).DispatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationWorkerService_DispatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationWorkerServiceServer).DispatchTask(ctx, req.(*DispatchTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationWorkerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationWorkerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationWorkerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationWorkerServiceServer).Health(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutomationWorkerService_ServiceDesc is the grpc.ServiceDesc for AutomationWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutomationWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gaia.workflow.v1.AutomationWorkerService",
	HandlerType: (*AutomationWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchTask",
			Handler:    _AutomationWorkerService_DispatchTask_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _AutomationWorkerService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "components/workflow/transport/grpc/proto/workflow.proto",
}
