// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: components/jobs/pb/job_admin.proto

package jobspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{0}
}

type JobItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SystemName    string                 `protobuf:"bytes,2,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	JobName       string                 `protobuf:"bytes,3,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobType       string                 `protobuf:"bytes,4,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	CronExpr      string                 `protobuf:"bytes,5,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ServiceName   string                 `protobuf:"bytes,7,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceMethod string                 `protobuf:"bytes,8,opt,name=service_method,json=serviceMethod,proto3" json:"service_method,omitempty"`
	Args          string                 `protobuf:"bytes,9,opt,name=args,proto3" json:"args,omitempty"`
	HookUrl       string                 `protobuf:"bytes,10,opt,name=hook_url,json=hookUrl,proto3" json:"hook_url,omitempty"`
	Timeout       int32                  `protobuf:"varint,11,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RunStatus     string                 `protobuf:"bytes,12,opt,name=run_status,json=runStatus,proto3" json:"run_status,omitempty"`
	LeaseOwner    string                 `protobuf:"bytes,13,opt,name=lease_owner,json=leaseOwner,proto3" json:"lease_owner,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastRunTime   *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=last_run_time,json=lastRunTime,proto3" json:"last_run_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobItem) Reset() {
	*x = JobItem{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobItem) ProtoMessage() {}

func (x *JobItem) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobItem.ProtoReflect.Descriptor instead.
func (*JobItem) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{1}
}

func (x *JobItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobItem) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

func (x *JobItem) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *JobItem) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *JobItem) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *JobItem) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *JobItem) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *JobItem) GetServiceMethod() string {
	if x != nil {
		return x.ServiceMethod
	}
	return ""
}

func (x *JobItem) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *JobItem) GetHookUrl() string {
	if x != nil {
		return x.HookUrl
	}
	return ""
}

func (x *JobItem) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *JobItem) GetRunStatus() string {
	if x != nil {
		return x.RunStatus
	}
	return ""
}

func (x *JobItem) GetLeaseOwner() string {
	if x != nil {
		return x.LeaseOwner
	}
	return ""
}

func (x *JobItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *JobItem) GetLastRunTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunTime
	}
	return nil
}

type ListJobsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemName    string                 `protobuf:"bytes,1,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	JobType       string                 `protobuf:"bytes,2,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	JobName       string                 `protobuf:"bytes,3,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Enabled       *bool                  `protobuf:"varint,4,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Page          int64                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsReq) Reset() {
	*x = ListJobsReq{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsReq) ProtoMessage() {}

func (x *ListJobsReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsReq.ProtoReflect.Descriptor instead.
func (*ListJobsReq) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListJobsReq) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

func (x *ListJobsReq) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *ListJobsReq) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *ListJobsReq) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *ListJobsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListJobsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListJobsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobItem             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResp) Reset() {
	*x = ListJobsResp{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResp) ProtoMessage() {}

func (x *ListJobsResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResp.ProtoReflect.Descriptor instead.
func (*ListJobsResp) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListJobsResp) GetJobs() []*JobItem {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobReq) Reset() {
	*x = GetJobReq{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobReq) ProtoMessage() {}

func (x *GetJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobReq.ProtoReflect.Descriptor instead.
func (*GetJobReq) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemName    string                 `protobuf:"bytes,1,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	JobName       string                 `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobType       string                 `protobuf:"bytes,3,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	CronExpr      string                 `protobuf:"bytes,4,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	ServiceName   string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceMethod string                 `protobuf:"bytes,6,opt,name=service_method,json=serviceMethod,proto3" json:"service_method,omitempty"`
	Args          string                 `protobuf:"bytes,7,opt,name=args,proto3" json:"args,omitempty"`
	HookUrl       string                 `protobuf:"bytes,8,opt,name=hook_url,json=hookUrl,proto3" json:"hook_url,omitempty"`
	Timeout       int32                  `protobuf:"varint,9,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Enabled       bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobReq) Reset() {
	*x = CreateJobReq{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobReq) ProtoMessage() {}

func (x *CreateJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobReq.ProtoReflect.Descriptor instead.
func (*CreateJobReq) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{5}
}

func (x *CreateJobReq) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

func (x *CreateJobReq) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *CreateJobReq) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *CreateJobReq) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *CreateJobReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CreateJobReq) GetServiceMethod() string {
	if x != nil {
		return x.ServiceMethod
	}
	return ""
}

func (x *CreateJobReq) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *CreateJobReq) GetHookUrl() string {
	if x != nil {
		return x.HookUrl
	}
	return ""
}

func (x *CreateJobReq) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *CreateJobReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type CreateJobResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobResp) Reset() {
	*x = CreateJobResp{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobResp) ProtoMessage() {}

func (x *CreateJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobResp.ProtoReflect.Descriptor instead.
func (*CreateJobResp) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{6}
}

func (x *CreateJobResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SystemName    string                 `protobuf:"bytes,2,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	JobName       string                 `protobuf:"bytes,3,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobType       string                 `protobuf:"bytes,4,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	CronExpr      string                 `protobuf:"bytes,5,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	ServiceName   string                 `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceMethod string                 `protobuf:"bytes,7,opt,name=service_method,json=serviceMethod,proto3" json:"service_method,omitempty"`
	Args          string                 `protobuf:"bytes,8,opt,name=args,proto3" json:"args,omitempty"`
	HookUrl       string                 `protobuf:"bytes,9,opt,name=hook_url,json=hookUrl,proto3" json:"hook_url,omitempty"`
	Timeout       int32                  `protobuf:"varint,10,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Enabled       bool                   `protobuf:"varint,11,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobReq) Reset() {
	*x = UpdateJobReq{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobReq) ProtoMessage() {}

func (x *UpdateJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobReq.ProtoReflect.Descriptor instead.
func (*UpdateJobReq) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateJobReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateJobReq) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

func (x *UpdateJobReq) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *UpdateJobReq) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *UpdateJobReq) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *UpdateJobReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UpdateJobReq) GetServiceMethod() string {
	if x != nil {
		return x.ServiceMethod
	}
	return ""
}

func (x *UpdateJobReq) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *UpdateJobReq) GetHookUrl() string {
	if x != nil {
		return x.HookUrl
	}
	return ""
}

func (x *UpdateJobReq) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *UpdateJobReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpdateJobResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Affected      int64                  `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobResp) Reset() {
	*x = UpdateJobResp{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobResp) ProtoMessage() {}

func (x *UpdateJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobResp.ProtoReflect.Descriptor instead.
func (*UpdateJobResp) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateJobResp) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

type DeleteJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobReq) Reset() {
	*x = DeleteJobReq{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobReq) ProtoMessage() {}

func (x *DeleteJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobReq.ProtoReflect.Descriptor instead.
func (*DeleteJobReq) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteJobReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ToggleJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled       *bool                  `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleJobReq) Reset() {
	*x = ToggleJobReq{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleJobReq) ProtoMessage() {}

func (x *ToggleJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleJobReq.ProtoReflect.Descriptor instead.
func (*ToggleJobReq) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ToggleJobReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ToggleJobReq) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type ExecuteJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJobReq) Reset() {
	*x = ExecuteJobReq{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJobReq) ProtoMessage() {}

func (x *ExecuteJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJobReq.ProtoReflect.Descriptor instead.
func (*ExecuteJobReq) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteJobReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type JobRecordItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SystemName    string                 `protobuf:"bytes,2,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	JobName       string                 `protobuf:"bytes,3,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobType       string                 `protobuf:"bytes,4,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	ServiceName   string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceMethod string                 `protobuf:"bytes,6,opt,name=service_method,json=serviceMethod,proto3" json:"service_method,omitempty"`
	Result        string                 `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	RunResult     string                 `protobuf:"bytes,9,opt,name=run_result,json=runResult,proto3" json:"run_result,omitempty"`
	DurationMs    int64                  `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	InstanceId    string                 `protobuf:"bytes,11,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRecordItem) Reset() {
	*x = JobRecordItem{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRecordItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRecordItem) ProtoMessage() {}

func (x *JobRecordItem) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRecordItem.ProtoReflect.Descriptor instead.
func (*JobRecordItem) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{12}
}

func (x *JobRecordItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobRecordItem) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

func (x *JobRecordItem) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *JobRecordItem) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *JobRecordItem) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *JobRecordItem) GetServiceMethod() string {
	if x != nil {
		return x.ServiceMethod
	}
	return ""
}

func (x *JobRecordItem) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *JobRecordItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobRecordItem) GetRunResult() string {
	if x != nil {
		return x.RunResult
	}
	return ""
}

func (x *JobRecordItem) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *JobRecordItem) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *JobRecordItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobRecordItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListRecordsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsReq) Reset() {
	*x = ListRecordsReq{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsReq) ProtoMessage() {}

func (x *ListRecordsReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsReq.ProtoReflect.Descriptor instead.
func (*ListRecordsReq) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{13}
}

func (x *ListRecordsReq) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *ListRecordsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRecordsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRecordsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRecordsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*JobRecordItem       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResp) Reset() {
	*x = ListRecordsResp{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResp) ProtoMessage() {}

func (x *ListRecordsResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResp.ProtoReflect.Descriptor instead.
func (*ListRecordsResp) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ListRecordsResp) GetRecords() []*JobRecordItem {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListRecordsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RunningJobItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SystemName    string                 `protobuf:"bytes,2,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	JobName       string                 `protobuf:"bytes,3,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobType       string                 `protobuf:"bytes,4,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	ServiceName   string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceMethod string                 `protobuf:"bytes,6,opt,name=service_method,json=serviceMethod,proto3" json:"service_method,omitempty"`
	RunStatus     string                 `protobuf:"bytes,7,opt,name=run_status,json=runStatus,proto3" json:"run_status,omitempty"`
	LeaseOwner    string                 `protobuf:"bytes,8,opt,name=lease_owner,json=leaseOwner,proto3" json:"lease_owner,omitempty"`
	LastRunTime   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_run_time,json=lastRunTime,proto3" json:"last_run_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningJobItem) Reset() {
	*x = RunningJobItem{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningJobItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningJobItem) ProtoMessage() {}

func (x *RunningJobItem) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningJobItem.ProtoReflect.Descriptor instead.
func (*RunningJobItem) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{15}
}

func (x *RunningJobItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RunningJobItem) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

func (x *RunningJobItem) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *RunningJobItem) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *RunningJobItem) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RunningJobItem) GetServiceMethod() string {
	if x != nil {
		return x.ServiceMethod
	}
	return ""
}

func (x *RunningJobItem) GetRunStatus() string {
	if x != nil {
		return x.RunStatus
	}
	return ""
}

func (x *RunningJobItem) GetLeaseOwner() string {
	if x != nil {
		return x.LeaseOwner
	}
	return ""
}

func (x *RunningJobItem) GetLastRunTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunTime
	}
	return nil
}

type RunningJobsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       []*RunningJobItem      `protobuf:"bytes,1,rep,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningJobsResp) Reset() {
	*x = RunningJobsResp{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningJobsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningJobsResp) ProtoMessage() {}

func (x *RunningJobsResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningJobsResp.ProtoReflect.Descriptor instead.
func (*RunningJobsResp) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{16}
}

func (x *RunningJobsResp) GetRunning() []*RunningJobItem {
	if x != nil {
		return x.Running
	}
	return nil
}

type JobStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Enabled       int64                  `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Disabled      int64                  `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Running       int64                  `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	ByType        map[string]int64       `protobuf:"bytes,5,rep,name=by_type,json=byType,proto3" json:"by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatsResp) Reset() {
	*x = JobStatsResp{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatsResp) ProtoMessage() {}

func (x *JobStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatsResp.ProtoReflect.Descriptor instead.
func (*JobStatsResp) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{17}
}

func (x *JobStatsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *JobStatsResp) GetEnabled() int64 {
	if x != nil {
		return x.Enabled
	}
	return 0
}

func (x *JobStatsResp) GetDisabled() int64 {
	if x != nil {
		return x.Disabled
	}
	return 0
}

func (x *JobStatsResp) GetRunning() int64 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *JobStatsResp) GetByType() map[string]int64 {
	if x != nil {
		return x.ByType
	}
	return nil
}

type SchedulerStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ActiveJobs    int32                  `protobuf:"varint,3,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	ExecCount     int64                  `protobuf:"varint,4,opt,name=exec_count,json=execCount,proto3" json:"exec_count,omitempty"`
	SuccessCount  int64                  `protobuf:"varint,5,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedCount   int64                  `protobuf:"varint,6,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	PanicCount    int64                  `protobuf:"varint,7,opt,name=panic_count,json=panicCount,proto3" json:"panic_count,omitempty"`
	SkipCount     int64                  `protobuf:"varint,8,opt,name=skip_count,json=skipCount,proto3" json:"skip_count,omitempty"`
	TimeoutCount  int64                  `protobuf:"varint,9,opt,name=timeout_count,json=timeoutCount,proto3" json:"timeout_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerStatusResp) Reset() {
	*x = SchedulerStatusResp{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerStatusResp) ProtoMessage() {}

func (x *SchedulerStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerStatusResp.ProtoReflect.Descriptor instead.
func (*SchedulerStatusResp) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{18}
}

func (x *SchedulerStatusResp) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SchedulerStatusResp) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *SchedulerStatusResp) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *SchedulerStatusResp) GetExecCount() int64 {
	if x != nil {
		return x.ExecCount
	}
	return 0
}

func (x *SchedulerStatusResp) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *SchedulerStatusResp) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *SchedulerStatusResp) GetPanicCount() int64 {
	if x != nil {
		return x.PanicCount
	}
	return 0
}

func (x *SchedulerStatusResp) GetSkipCount() int64 {
	if x != nil {
		return x.SkipCount
	}
	return 0
}

func (x *SchedulerStatusResp) GetTimeoutCount() int64 {
	if x != nil {
		return x.TimeoutCount
	}
	return 0
}

type RegisterServiceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemName    string                 `protobuf:"bytes,1,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Methods       []string               `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceReq) Reset() {
	*x = RegisterServiceReq{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceReq) ProtoMessage() {}

func (x *RegisterServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceReq.ProtoReflect.Descriptor instead.
func (*RegisterServiceReq) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterServiceReq) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

func (x *RegisterServiceReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterServiceReq) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type ListServicesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemName    string                 `protobuf:"bytes,1,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesReq) Reset() {
	*x = ListServicesReq{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesReq) ProtoMessage() {}

func (x *ListServicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesReq.ProtoReflect.Descriptor instead.
func (*ListServicesReq) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ListServicesReq) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

type ListServicesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*RegisteredService   `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResp) Reset() {
	*x = ListServicesResp{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResp) ProtoMessage() {}

func (x *ListServicesResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResp.ProtoReflect.Descriptor instead.
func (*ListServicesResp) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{21}
}

func (x *ListServicesResp) GetServices() []*RegisteredService {
	if x != nil {
		return x.Services
	}
	return nil
}

type RegisteredService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemName    string                 `protobuf:"bytes,1,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Methods       []string               `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	Executable    bool                   `protobuf:"varint,4,opt,name=executable,proto3" json:"executable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisteredService) Reset() {
	*x = RegisteredService{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredService) ProtoMessage() {}

func (x *RegisteredService) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredService.ProtoReflect.Descriptor instead.
func (*RegisteredService) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{22}
}

func (x *RegisteredService) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

func (x *RegisteredService) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisteredService) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *RegisteredService) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

type HealthResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	InstanceId     string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	DbSchema       string                 `protobuf:"bytes,3,opt,name=db_schema,json=dbSchema,proto3" json:"db_schema,omitempty"`
	HaDisabled     bool                   `protobuf:"varint,4,opt,name=ha_disabled,json=haDisabled,proto3" json:"ha_disabled,omitempty"`
	RunningJobNum  int32                  `protobuf:"varint,5,opt,name=running_job_num,json=runningJobNum,proto3" json:"running_job_num,omitempty"`
	WaitJobNum     int32                  `protobuf:"varint,6,opt,name=wait_job_num,json=waitJobNum,proto3" json:"wait_job_num,omitempty"`
	DisabledJobNum int32                  `protobuf:"varint,7,opt,name=disabled_job_num,json=disabledJobNum,proto3" json:"disabled_job_num,omitempty"`
	MyOwnedJobNum  int32                  `protobuf:"varint,8,opt,name=my_owned_job_num,json=myOwnedJobNum,proto3" json:"my_owned_job_num,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthResp) Reset() {
	*x = HealthResp{}
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResp) ProtoMessage() {}

func (x *HealthResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_jobs_pb_job_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResp.ProtoReflect.Descriptor instead.
func (*HealthResp) Descriptor() ([]byte, []int) {
	return file_components_jobs_pb_job_admin_proto_rawDescGZIP(), []int{23}
}

func (x *HealthResp) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResp) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HealthResp) GetDbSchema() string {
	if x != nil {
		return x.DbSchema
	}
	return ""
}

func (x *HealthResp) GetHaDisabled() bool {
	if x != nil {
		return x.HaDisabled
	}
	return false
}

func (x *HealthResp) GetRunningJobNum() int32 {
	if x != nil {
		return x.RunningJobNum
	}
	return 0
}

func (x *HealthResp) GetWaitJobNum() int32 {
	if x != nil {
		return x.WaitJobNum
	}
	return 0
}

func (x *HealthResp) GetDisabledJobNum() int32 {
	if x != nil {
		return x.DisabledJobNum
	}
	return 0
}

func (x *HealthResp) GetMyOwnedJobNum() int32 {
	if x != nil {
		return x.MyOwnedJobNum
	}
	return 0
}

var File_components_jobs_pb_job_admin_proto protoreflect.FileDescriptor

const file_components_jobs_pb_job_admin_proto_rawDesc = "" +
	"\n" +
	"\"components/jobs/pb/job_admin.proto\x12\ajobs.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\xb0\x04\n" +
	"\aJobItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vsystem_name\x18\x02 \x01(\tR\n" +
	"systemName\x12\x19\n" +
	"\bjob_name\x18\x03 \x01(\tR\ajobName\x12\x19\n" +
	"\bjob_type\x18\x04 \x01(\tR\ajobType\x12\x1b\n" +
	"\tcron_expr\x18\x05 \x01(\tR\bcronExpr\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12!\n" +
	"\fservice_name\x18\a \x01(\tR\vserviceName\x12%\n" +
	"\x0eservice_method\x18\b \x01(\tR\rserviceMethod\x12\x12\n" +
	"\x04args\x18\t \x01(\tR\x04args\x12\x19\n" +
	"\bhook_url\x18\n" +
	" \x01(\tR\ahookUrl\x12\x18\n" +
	"\atimeout\x18\v \x01(\x05R\atimeout\x12\x1d\n" +
	"\n" +
	"run_status\x18\f \x01(\tR\trunStatus\x12\x1f\n" +
	"\vlease_owner\x18\r \x01(\tR\n" +
	"leaseOwner\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\rlast_run_time\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vlastRunTime\"\xc0\x01\n" +
	"\vListJobsReq\x12\x1f\n" +
	"\vsystem_name\x18\x01 \x01(\tR\n" +
	"systemName\x12\x19\n" +
	"\bjob_type\x18\x02 \x01(\tR\ajobType\x12\x19\n" +
	"\bjob_name\x18\x03 \x01(\tR\ajobName\x12\x1d\n" +
	"\aenabled\x18\x04 \x01(\bH\x00R\aenabled\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x03R\bpageSizeB\n" +
	"\n" +
	"\b_enabled\"J\n" +
	"\fListJobsResp\x12$\n" +
	"\x04jobs\x18\x01 \x03(\v2\x10.jobs.v1.JobItemR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x1b\n" +
	"\tGetJobReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xaf\x02\n" +
	"\fCreateJobReq\x12\x1f\n" +
	"\vsystem_name\x18\x01 \x01(\tR\n" +
	"systemName\x12\x19\n" +
	"\bjob_name\x18\x02 \x01(\tR\ajobName\x12\x19\n" +
	"\bjob_type\x18\x03 \x01(\tR\ajobType\x12\x1b\n" +
	"\tcron_expr\x18\x04 \x01(\tR\bcronExpr\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12%\n" +
	"\x0eservice_method\x18\x06 \x01(\tR\rserviceMethod\x12\x12\n" +
	"\x04args\x18\a \x01(\tR\x04args\x12\x19\n" +
	"\bhook_url\x18\b \x01(\tR\ahookUrl\x12\x18\n" +
	"\atimeout\x18\t \x01(\x05R\atimeout\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\"\x1f\n" +
	"\rCreateJobResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xbf\x02\n" +
	"\fUpdateJobReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vsystem_name\x18\x02 \x01(\tR\n" +
	"systemName\x12\x19\n" +
	"\bjob_name\x18\x03 \x01(\tR\ajobName\x12\x19\n" +
	"\bjob_type\x18\x04 \x01(\tR\ajobType\x12\x1b\n" +
	"\tcron_expr\x18\x05 \x01(\tR\bcronExpr\x12!\n" +
	"\fservice_name\x18\x06 \x01(\tR\vserviceName\x12%\n" +
	"\x0eservice_method\x18\a \x01(\tR\rserviceMethod\x12\x12\n" +
	"\x04args\x18\b \x01(\tR\x04args\x12\x19\n" +
	"\bhook_url\x18\t \x01(\tR\ahookUrl\x12\x18\n" +
	"\atimeout\x18\n" +
	" \x01(\x05R\atimeout\x12\x18\n" +
	"\aenabled\x18\v \x01(\bR\aenabled\"+\n" +
	"\rUpdateJobResp\x12\x1a\n" +
	"\baffected\x18\x01 \x01(\x03R\baffected\"\x1e\n" +
	"\fDeleteJobReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"I\n" +
	"\fToggleJobReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\aenabled\x18\x02 \x01(\bH\x00R\aenabled\x88\x01\x01B\n" +
	"\n" +
	"\b_enabled\"\x1f\n" +
	"\rExecuteJobReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc5\x03\n" +
	"\rJobRecordItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vsystem_name\x18\x02 \x01(\tR\n" +
	"systemName\x12\x19\n" +
	"\bjob_name\x18\x03 \x01(\tR\ajobName\x12\x19\n" +
	"\bjob_type\x18\x04 \x01(\tR\ajobType\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12%\n" +
	"\x0eservice_method\x18\x06 \x01(\tR\rserviceMethod\x12\x16\n" +
	"\x06result\x18\a \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"run_result\x18\t \x01(\tR\trunResult\x12\x1f\n" +
	"\vduration_ms\x18\n" +
	" \x01(\x03R\n" +
	"durationMs\x12\x1f\n" +
	"\vinstance_id\x18\v \x01(\tR\n" +
	"instanceId\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"p\n" +
	"\x0eListRecordsReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"Y\n" +
	"\x0fListRecordsResp\x120\n" +
	"\arecords\x18\x01 \x03(\v2\x16.jobs.v1.JobRecordItemR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xc1\x02\n" +
	"\x0eRunningJobItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vsystem_name\x18\x02 \x01(\tR\n" +
	"systemName\x12\x19\n" +
	"\bjob_name\x18\x03 \x01(\tR\ajobName\x12\x19\n" +
	"\bjob_type\x18\x04 \x01(\tR\ajobType\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12%\n" +
	"\x0eservice_method\x18\x06 \x01(\tR\rserviceMethod\x12\x1d\n" +
	"\n" +
	"run_status\x18\a \x01(\tR\trunStatus\x12\x1f\n" +
	"\vlease_owner\x18\b \x01(\tR\n" +
	"leaseOwner\x12>\n" +
	"\rlast_run_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vlastRunTime\"D\n" +
	"\x0fRunningJobsResp\x121\n" +
	"\arunning\x18\x01 \x03(\v2\x17.jobs.v1.RunningJobItemR\arunning\"\xeb\x01\n" +
	"\fJobStatsResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\x03R\aenabled\x12\x1a\n" +
	"\bdisabled\x18\x03 \x01(\x03R\bdisabled\x12\x18\n" +
	"\arunning\x18\x04 \x01(\x03R\arunning\x12:\n" +
	"\aby_type\x18\x05 \x03(\v2!.jobs.v1.JobStatsResp.ByTypeEntryR\x06byType\x1a9\n" +
	"\vByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xbd\x02\n" +
	"\x13SchedulerStatusResp\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12\x1f\n" +
	"\vactive_jobs\x18\x03 \x01(\x05R\n" +
	"activeJobs\x12\x1d\n" +
	"\n" +
	"exec_count\x18\x04 \x01(\x03R\texecCount\x12#\n" +
	"\rsuccess_count\x18\x05 \x01(\x03R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x06 \x01(\x03R\vfailedCount\x12\x1f\n" +
	"\vpanic_count\x18\a \x01(\x03R\n" +
	"panicCount\x12\x1d\n" +
	"\n" +
	"skip_count\x18\b \x01(\x03R\tskipCount\x12#\n" +
	"\rtimeout_count\x18\t \x01(\x03R\ftimeoutCount\"r\n" +
	"\x12RegisterServiceReq\x12\x1f\n" +
	"\vsystem_name\x18\x01 \x01(\tR\n" +
	"systemName\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\amethods\x18\x03 \x03(\tR\amethods\"2\n" +
	"\x0fListServicesReq\x12\x1f\n" +
	"\vsystem_name\x18\x01 \x01(\tR\n" +
	"systemName\"J\n" +
	"\x10ListServicesResp\x126\n" +
	"\bservices\x18\x01 \x03(\v2\x1a.jobs.v1.RegisteredServiceR\bservices\"\x91\x01\n" +
	"\x11RegisteredService\x12\x1f\n" +
	"\vsystem_name\x18\x01 \x01(\tR\n" +
	"systemName\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\amethods\x18\x03 \x03(\tR\amethods\x12\x1e\n" +
	"\n" +
	"executable\x18\x04 \x01(\bR\n" +
	"executable\"\xa2\x02\n" +
	"\n" +
	"HealthResp\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tdb_schema\x18\x03 \x01(\tR\bdbSchema\x12\x1f\n" +
	"\vha_disabled\x18\x04 \x01(\bR\n" +
	"haDisabled\x12&\n" +
	"\x0frunning_job_num\x18\x05 \x01(\x05R\rrunningJobNum\x12 \n" +
	"\fwait_job_num\x18\x06 \x01(\x05R\n" +
	"waitJobNum\x12(\n" +
	"\x10disabled_job_num\x18\a \x01(\x05R\x0edisabledJobNum\x12'\n" +
	"\x10my_owned_job_num\x18\b \x01(\x05R\rmyOwnedJobNum2\x98\a\n" +
	"\bJobAdmin\x127\n" +
	"\bListJobs\x12\x14.jobs.v1.ListJobsReq\x1a\x15.jobs.v1.ListJobsResp\x12.\n" +
	"\x06GetJob\x12\x12.jobs.v1.GetJobReq\x1a\x10.jobs.v1.JobItem\x12:\n" +
	"\tCreateJob\x12\x15.jobs.v1.CreateJobReq\x1a\x16.jobs.v1.CreateJobResp\x12:\n" +
	"\tUpdateJob\x12\x15.jobs.v1.UpdateJobReq\x1a\x16.jobs.v1.UpdateJobResp\x122\n" +
	"\tDeleteJob\x12\x15.jobs.v1.DeleteJobReq\x1a\x0e.jobs.v1.Empty\x122\n" +
	"\tToggleJob\x12\x15.jobs.v1.ToggleJobReq\x1a\x0e.jobs.v1.Empty\x124\n" +
	"\n" +
	"ExecuteJob\x12\x16.jobs.v1.ExecuteJobReq\x1a\x0e.jobs.v1.Empty\x12@\n" +
	"\vListRecords\x12\x17.jobs.v1.ListRecordsReq\x1a\x18.jobs.v1.ListRecordsResp\x12:\n" +
	"\x0eGetRunningJobs\x12\x0e.jobs.v1.Empty\x1a\x18.jobs.v1.RunningJobsResp\x121\n" +
	"\bGetStats\x12\x0e.jobs.v1.Empty\x1a\x15.jobs.v1.JobStatsResp\x12B\n" +
	"\x12GetSchedulerStatus\x12\x0e.jobs.v1.Empty\x1a\x1c.jobs.v1.SchedulerStatusResp\x120\n" +
	"\x0eStartScheduler\x12\x0e.jobs.v1.Empty\x1a\x0e.jobs.v1.Empty\x12/\n" +
	"\rStopScheduler\x12\x0e.jobs.v1.Empty\x1a\x0e.jobs.v1.Empty\x12>\n" +
	"\x0fRegisterService\x12\x1b.jobs.v1.RegisterServiceReq\x1a\x0e.jobs.v1.Empty\x12C\n" +
	"\fListServices\x12\x18.jobs.v1.ListServicesReq\x1a\x19.jobs.v1.ListServicesResp\x120\n" +
	"\tGetHealth\x12\x0e.jobs.v1.Empty\x1a\x13.jobs.v1.HealthRespB2Z0github.com/xxzhwl/gaia/components/jobs/pb;jobspbb\x06proto3"

var (
	file_components_jobs_pb_job_admin_proto_rawDescOnce sync.Once
	file_components_jobs_pb_job_admin_proto_rawDescData []byte
)

func file_components_jobs_pb_job_admin_proto_rawDescGZIP() []byte {
	file_components_jobs_pb_job_admin_proto_rawDescOnce.Do(func() {
		file_components_jobs_pb_job_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_jobs_pb_job_admin_proto_rawDesc), len(file_components_jobs_pb_job_admin_proto_rawDesc)))
	})
	return file_components_jobs_pb_job_admin_proto_rawDescData
}

var file_components_jobs_pb_job_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_components_jobs_pb_job_admin_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: jobs.v1.Empty
	(*JobItem)(nil),               // 1: jobs.v1.JobItem
	(*ListJobsReq)(nil),           // 2: jobs.v1.ListJobsReq
	(*ListJobsResp)(nil),          // 3: jobs.v1.ListJobsResp
	(*GetJobReq)(nil),             // 4: jobs.v1.GetJobReq
	(*CreateJobReq)(nil),          // 5: jobs.v1.CreateJobReq
	(*CreateJobResp)(nil),         // 6: jobs.v1.CreateJobResp
	(*UpdateJobReq)(nil),          // 7: jobs.v1.UpdateJobReq
	(*UpdateJobResp)(nil),         // 8: jobs.v1.UpdateJobResp
	(*DeleteJobReq)(nil),          // 9: jobs.v1.DeleteJobReq
	(*ToggleJobReq)(nil),          // 10: jobs.v1.ToggleJobReq
	(*ExecuteJobReq)(nil),         // 11: jobs.v1.ExecuteJobReq
	(*JobRecordItem)(nil),         // 12: jobs.v1.JobRecordItem
	(*ListRecordsReq)(nil),        // 13: jobs.v1.ListRecordsReq
	(*ListRecordsResp)(nil),       // 14: jobs.v1.ListRecordsResp
	(*RunningJobItem)(nil),        // 15: jobs.v1.RunningJobItem
	(*RunningJobsResp)(nil),       // 16: jobs.v1.RunningJobsResp
	(*JobStatsResp)(nil),          // 17: jobs.v1.JobStatsResp
	(*SchedulerStatusResp)(nil),   // 18: jobs.v1.SchedulerStatusResp
	(*RegisterServiceReq)(nil),    // 19: jobs.v1.RegisterServiceReq
	(*ListServicesReq)(nil),       // 20: jobs.v1.ListServicesReq
	(*ListServicesResp)(nil),      // 21: jobs.v1.ListServicesResp
	(*RegisteredService)(nil),     // 22: jobs.v1.RegisteredService
	(*HealthResp)(nil),            // 23: jobs.v1.HealthResp
	nil,                           // 24: jobs.v1.JobStatsResp.ByTypeEntry
	(*timestamppb.Timestamp)(nil), // 25: google.protobuf.Timestamp
}
var file_components_jobs_pb_job_admin_proto_depIdxs = []int32{
	25, // 0: jobs.v1.JobItem.created_at:type_name -> google.protobuf.Timestamp
	25, // 1: jobs.v1.JobItem.updated_at:type_name -> google.protobuf.Timestamp
	25, // 2: jobs.v1.JobItem.last_run_time:type_name -> google.protobuf.Timestamp
	1,  // 3: jobs.v1.ListJobsResp.jobs:type_name -> jobs.v1.JobItem
	25, // 4: jobs.v1.JobRecordItem.created_at:type_name -> google.protobuf.Timestamp
	25, // 5: jobs.v1.JobRecordItem.updated_at:type_name -> google.protobuf.Timestamp
	12, // 6: jobs.v1.ListRecordsResp.records:type_name -> jobs.v1.JobRecordItem
	25, // 7: jobs.v1.RunningJobItem.last_run_time:type_name -> google.protobuf.Timestamp
	15, // 8: jobs.v1.RunningJobsResp.running:type_name -> jobs.v1.RunningJobItem
	24, // 9: jobs.v1.JobStatsResp.by_type:type_name -> jobs.v1.JobStatsResp.ByTypeEntry
	22, // 10: jobs.v1.ListServicesResp.services:type_name -> jobs.v1.RegisteredService
	2,  // 11: jobs.v1.JobAdmin.ListJobs:input_type -> jobs.v1.ListJobsReq
	4,  // 12: jobs.v1.JobAdmin.GetJob:input_type -> jobs.v1.GetJobReq
	5,  // 13: jobs.v1.JobAdmin.CreateJob:input_type -> jobs.v1.CreateJobReq
	7,  // 14: jobs.v1.JobAdmin.UpdateJob:input_type -> jobs.v1.UpdateJobReq
	9,  // 15: jobs.v1.JobAdmin.DeleteJob:input_type -> jobs.v1.DeleteJobReq
	10, // 16: jobs.v1.JobAdmin.ToggleJob:input_type -> jobs.v1.ToggleJobReq
	11, // 17: jobs.v1.JobAdmin.ExecuteJob:input_type -> jobs.v1.ExecuteJobReq
	13, // 18: jobs.v1.JobAdmin.ListRecords:input_type -> jobs.v1.ListRecordsReq
	0,  // 19: jobs.v1.JobAdmin.GetRunningJobs:input_type -> jobs.v1.Empty
	0,  // 20: jobs.v1.JobAdmin.GetStats:input_type -> jobs.v1.Empty
	0,  // 21: jobs.v1.JobAdmin.GetSchedulerStatus:input_type -> jobs.v1.Empty
	0,  // 22: jobs.v1.JobAdmin.StartScheduler:input_type -> jobs.v1.Empty
	0,  // 23: jobs.v1.JobAdmin.StopScheduler:input_type -> jobs.v1.Empty
	19, // 24: jobs.v1.JobAdmin.RegisterService:input_type -> jobs.v1.RegisterServiceReq
	20, // 25: jobs.v1.JobAdmin.ListServices:input_type -> jobs.v1.ListServicesReq
	0,  // 26: jobs.v1.JobAdmin.GetHealth:input_type -> jobs.v1.Empty
	3,  // 27: jobs.v1.JobAdmin.ListJobs:output_type -> jobs.v1.ListJobsResp
	1,  // 28: jobs.v1.JobAdmin.GetJob:output_type -> jobs.v1.JobItem
	6,  // 29: jobs.v1.JobAdmin.CreateJob:output_type -> jobs.v1.CreateJobResp
	8,  // 30: jobs.v1.JobAdmin.UpdateJob:output_type -> jobs.v1.UpdateJobResp
	0,  // 31: jobs.v1.JobAdmin.DeleteJob:output_type -> jobs.v1.Empty
	0,  // 32: jobs.v1.JobAdmin.ToggleJob:output_type -> jobs.v1.Empty
	0,  // 33: jobs.v1.JobAdmin.ExecuteJob:output_type -> jobs.v1.Empty
	14, // 34: jobs.v1.JobAdmin.ListRecords:output_type -> jobs.v1.ListRecordsResp
	16, // 35: jobs.v1.JobAdmin.GetRunningJobs:output_type -> jobs.v1.RunningJobsResp
	17, // 36: jobs.v1.JobAdmin.GetStats:output_type -> jobs.v1.JobStatsResp
	18, // 37: jobs.v1.JobAdmin.GetSchedulerStatus:output_type -> jobs.v1.SchedulerStatusResp
	0,  // 38: jobs.v1.JobAdmin.StartScheduler:output_type -> jobs.v1.Empty
	0,  // 39: jobs.v1.JobAdmin.StopScheduler:output_type -> jobs.v1.Empty
	0,  // 40: jobs.v1.JobAdmin.RegisterService:output_type -> jobs.v1.Empty
	21, // 41: jobs.v1.JobAdmin.ListServices:output_type -> jobs.v1.ListServicesResp
	23, // 42: jobs.v1.JobAdmin.GetHealth:output_type -> jobs.v1.HealthResp
	27, // [27:43] is the sub-list for method output_type
	11, // [11:27] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_components_jobs_pb_job_admin_proto_init() }
func file_components_jobs_pb_job_admin_proto_init() {
	if File_components_jobs_pb_job_admin_proto != nil {
		return
	}
	file_components_jobs_pb_job_admin_proto_msgTypes[2].OneofWrappers = []any{}
	file_components_jobs_pb_job_admin_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_jobs_pb_job_admin_proto_rawDesc), len(file_components_jobs_pb_job_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_components_jobs_pb_job_admin_proto_goTypes,
		DependencyIndexes: file_components_jobs_pb_job_admin_proto_depIdxs,
		MessageInfos:      file_components_jobs_pb_job_admin_proto_msgTypes,
	}.Build()
	File_components_jobs_pb_job_admin_proto = out.File
	file_components_jobs_pb_job_admin_proto_goTypes = nil
	file_components_jobs_pb_job_admin_proto_depIdxs = nil
}
