// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: components/jobs/pb/job_admin.proto

package jobspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobAdmin_ListJobs_FullMethodName           = "/jobs.v1.JobAdmin/ListJobs"
	JobAdmin_GetJob_FullMethodName             = "/jobs.v1.JobAdmin/GetJob"
	JobAdmin_CreateJob_FullMethodName          = "/jobs.v1.JobAdmin/CreateJob"
	JobAdmin_UpdateJob_FullMethodName          = "/jobs.v1.JobAdmin/UpdateJob"
	JobAdmin_DeleteJob_FullMethodName          = "/jobs.v1.JobAdmin/DeleteJob"
	JobAdmin_ToggleJob_FullMethodName          = "/jobs.v1.JobAdmin/ToggleJob"
	JobAdmin_ExecuteJob_FullMethodName         = "/jobs.v1.JobAdmin/ExecuteJob"
	JobAdmin_ListRecords_FullMethodName        = "/jobs.v1.JobAdmin/ListRecords"
	JobAdmin_GetRunningJobs_FullMethodName     = "/jobs.v1.JobAdmin/GetRunningJobs"
	JobAdmin_GetStats_FullMethodName           = "/jobs.v1.JobAdmin/GetStats"
	JobAdmin_GetSchedulerStatus_FullMethodName = "/jobs.v1.JobAdmin/GetSchedulerStatus"
	JobAdmin_StartScheduler_FullMethodName     = "/jobs.v1.JobAdmin/StartScheduler"
	JobAdmin_StopScheduler_FullMethodName      = "/jobs.v1.JobAdmin/StopScheduler"
	JobAdmin_RegisterService_FullMethodName    = "/jobs.v1.JobAdmin/RegisterService"
	JobAdmin_ListServices_FullMethodName       = "/jobs.v1.JobAdmin/ListServices"
	JobAdmin_GetHealth_FullMethodName          = "/jobs.v1.JobAdmin/GetHealth"
)

// JobAdminClient is the client API for JobAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobAdminClient interface {
	ListJobs(ctx context.Context, in *ListJobsReq, opts ...grpc.CallOption) (*ListJobsResp, error)
	GetJob(ctx context.Context, in *GetJobReq, opts ...grpc.CallOption) (*JobItem, error)
	CreateJob(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobResp, error)
	UpdateJob(ctx context.Context, in *UpdateJobReq, opts ...grpc.CallOption) (*UpdateJobResp, error)
	DeleteJob(ctx context.Context, in *DeleteJobReq, opts ...grpc.CallOption) (*Empty, error)
	ToggleJob(ctx context.Context, in *ToggleJobReq, opts ...grpc.CallOption) (*Empty, error)
	ExecuteJob(ctx context.Context, in *ExecuteJobReq, opts ...grpc.CallOption) (*Empty, error)
	ListRecords(ctx context.Context, in *ListRecordsReq, opts ...grpc.CallOption) (*ListRecordsResp, error)
	GetRunningJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RunningJobsResp, error)
	GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JobStatsResp, error)
	GetSchedulerStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SchedulerStatusResp, error)
	StartScheduler(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	StopScheduler(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	RegisterService(ctx context.Context, in *RegisterServiceReq, opts ...grpc.CallOption) (*Empty, error)
	ListServices(ctx context.Context, in *ListServicesReq, opts ...grpc.CallOption) (*ListServicesResp, error)
	GetHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResp, error)
}

type jobAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewJobAdminClient(cc grpc.ClientConnInterface) JobAdminClient {
	return &jobAdminClient{cc}
}

func (c *jobAdminClient) ListJobs(ctx context.Context, in *ListJobsReq, opts ...grpc.CallOption) (*ListJobsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResp)
	err := c.cc.Invoke(ctx, JobAdmin_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) GetJob(ctx context.Context, in *GetJobReq, opts ...grpc.CallOption) (*JobItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobItem)
	err := c.cc.Invoke(ctx, JobAdmin_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) CreateJob(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJobResp)
	err := c.cc.Invoke(ctx, JobAdmin_CreateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) UpdateJob(ctx context.Context, in *UpdateJobReq, opts ...grpc.CallOption) (*UpdateJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJobResp)
	err := c.cc.Invoke(ctx, JobAdmin_UpdateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) DeleteJob(ctx context.Context, in *DeleteJobReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, JobAdmin_DeleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) ToggleJob(ctx context.Context, in *ToggleJobReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, JobAdmin_ToggleJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) ExecuteJob(ctx context.Context, in *ExecuteJobReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, JobAdmin_ExecuteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) ListRecords(ctx context.Context, in *ListRecordsReq, opts ...grpc.CallOption) (*ListRecordsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecordsResp)
	err := c.cc.Invoke(ctx, JobAdmin_ListRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) GetRunningJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RunningJobsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunningJobsResp)
	err := c.cc.Invoke(ctx, JobAdmin_GetRunningJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JobStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatsResp)
	err := c.cc.Invoke(ctx, JobAdmin_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) GetSchedulerStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SchedulerStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerStatusResp)
	err := c.cc.Invoke(ctx, JobAdmin_GetSchedulerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) StartScheduler(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, JobAdmin_StartScheduler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) StopScheduler(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, JobAdmin_StopScheduler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) RegisterService(ctx context.Context, in *RegisterServiceReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, JobAdmin_RegisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) ListServices(ctx context.Context, in *ListServicesReq, opts ...grpc.CallOption) (*ListServicesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResp)
	err := c.cc.Invoke(ctx, JobAdmin_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAdminClient) GetHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResp)
	err := c.cc.Invoke(ctx, JobAdmin_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobAdminServer is the server API for JobAdmin service.
// All implementations must embed UnimplementedJobAdminServer
// for forward compatibility.
type JobAdminServer interface {
	ListJobs(context.Context, *ListJobsReq) (*ListJobsResp, error)
	GetJob(context.Context, *GetJobReq) (*JobItem, error)
	CreateJob(context.Context, *CreateJobReq) (*CreateJobResp, error)
	UpdateJob(context.Context, *UpdateJobReq) (*UpdateJobResp, error)
	DeleteJob(context.Context, *DeleteJobReq) (*Empty, error)
	ToggleJob(context.Context, *ToggleJobReq) (*Empty, error)
	ExecuteJob(context.Context, *ExecuteJobReq) (*Empty, error)
	ListRecords(context.Context, *ListRecordsReq) (*ListRecordsResp, error)
	GetRunningJobs(context.Context, *Empty) (*RunningJobsResp, error)
	GetStats(context.Context, *Empty) (*JobStatsResp, error)
	GetSchedulerStatus(context.Context, *Empty) (*SchedulerStatusResp, error)
	StartScheduler(context.Context, *Empty) (*Empty, error)
	StopScheduler(context.Context, *Empty) (*Empty, error)
	RegisterService(context.Context, *RegisterServiceReq) (*Empty, error)
	ListServices(context.Context, *ListServicesReq) (*ListServicesResp, error)
	GetHealth(context.Context, *Empty) (*HealthResp, error)
	mustEmbedUnimplementedJobAdminServer()
}

// UnimplementedJobAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobAdminServer struct{}

func (UnimplementedJobAdminServer) ListJobs(context.Context, *ListJobsReq) (*ListJobsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedJobAdminServer) GetJob(context.Context, *GetJobReq) (*JobItem, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedJobAdminServer) CreateJob(context.Context, *CreateJobReq) (*CreateJobResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedJobAdminServer) UpdateJob(context.Context, *UpdateJobReq) (*UpdateJobResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateJob not implemented")
}
func (UnimplementedJobAdminServer) DeleteJob(context.Context, *DeleteJobReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteJob not implemented")
}
func (UnimplementedJobAdminServer) ToggleJob(context.Context, *ToggleJobReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleJob not implemented")
}
func (UnimplementedJobAdminServer) ExecuteJob(context.Context, *ExecuteJobReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteJob not implemented")
}
func (UnimplementedJobAdminServer) ListRecords(context.Context, *ListRecordsReq) (*ListRecordsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecords not implemented")
}
func (UnimplementedJobAdminServer) GetRunningJobs(context.Context, *Empty) (*RunningJobsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunningJobs not implemented")
}
func (UnimplementedJobAdminServer) GetStats(context.Context, *Empty) (*JobStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedJobAdminServer) GetSchedulerStatus(context.Context, *Empty) (*SchedulerStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchedulerStatus not implemented")
}
func (UnimplementedJobAdminServer) StartScheduler(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StartScheduler not implemented")
}
func (UnimplementedJobAdminServer) StopScheduler(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopScheduler not implemented")
}
func (UnimplementedJobAdminServer) RegisterService(context.Context, *RegisterServiceReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterService not implemented")
}
func (UnimplementedJobAdminServer) ListServices(context.Context, *ListServicesReq) (*ListServicesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedJobAdminServer) GetHealth(context.Context, *Empty) (*HealthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedJobAdminServer) mustEmbedUnimplementedJobAdminServer() {}
func (UnimplementedJobAdminServer) testEmbeddedByValue()                  {}

// UnsafeJobAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobAdminServer will
// result in compilation errors.
type UnsafeJobAdminServer interface {
	mustEmbedUnimplementedJobAdminServer()
}

func RegisterJobAdminServer(s grpc.ServiceRegistrar, srv JobAdminServer) {
	// If the following call panics, it indicates UnimplementedJobAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobAdmin_ServiceDesc, srv)
}

func _JobAdmin_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).ListJobs(ctx, req.(*ListJobsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).GetJob(ctx, req.(*GetJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_CreateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).CreateJob(ctx, req.(*CreateJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_UpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).UpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_UpdateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).UpdateJob(ctx, req.(*UpdateJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_DeleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).DeleteJob(ctx, req.(*DeleteJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_ToggleJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).ToggleJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_ToggleJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).ToggleJob(ctx, req.(*ToggleJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_ExecuteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).ExecuteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_ExecuteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).ExecuteJob(ctx, req.(*ExecuteJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_ListRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).ListRecords(ctx, req.(*ListRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_GetRunningJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).GetRunningJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_GetRunningJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).GetRunningJobs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).GetStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_GetSchedulerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).GetSchedulerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_GetSchedulerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).GetSchedulerStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_StartScheduler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).StartScheduler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_StartScheduler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).StartScheduler(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_StopScheduler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).StopScheduler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_StopScheduler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).StopScheduler(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_RegisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).RegisterService(ctx, req.(*RegisterServiceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).ListServices(ctx, req.(*ListServicesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAdmin_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAdminServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAdmin_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAdminServer).GetHealth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// JobAdmin_ServiceDesc is the grpc.ServiceDesc for JobAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobs.v1.JobAdmin",
	HandlerType: (*JobAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListJobs",
			Handler:    _JobAdmin_ListJobs_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _JobAdmin_GetJob_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _JobAdmin_CreateJob_Handler,
		},
		{
			MethodName: "UpdateJob",
			Handler:    _JobAdmin_UpdateJob_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _JobAdmin_DeleteJob_Handler,
		},
		{
			MethodName: "ToggleJob",
			Handler:    _JobAdmin_ToggleJob_Handler,
		},
		{
			MethodName: "ExecuteJob",
			Handler:    _JobAdmin_ExecuteJob_Handler,
		},
		{
			MethodName: "ListRecords",
			Handler:    _JobAdmin_ListRecords_Handler,
		},
		{
			MethodName: "GetRunningJobs",
			Handler:    _JobAdmin_GetRunningJobs_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _JobAdmin_GetStats_Handler,
		},
		{
			MethodName: "GetSchedulerStatus",
			Handler:    _JobAdmin_GetSchedulerStatus_Handler,
		},
		{
			MethodName: "StartScheduler",
			Handler:    _JobAdmin_StartScheduler_Handler,
		},
		{
			MethodName: "StopScheduler",
			Handler:    _JobAdmin_StopScheduler_Handler,
		},
		{
			MethodName: "RegisterService",
			Handler:    _JobAdmin_RegisterService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _JobAdmin_ListServices_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _JobAdmin_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "components/jobs/pb/job_admin.proto",
}
