// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: components/asynctask/pb/async_task_admin.proto

package asynctaskpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{0}
}

type TaskItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskName        string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Theme           string                 `protobuf:"bytes,3,opt,name=theme,proto3" json:"theme,omitempty"`
	ServiceName     string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MethodName      string                 `protobuf:"bytes,5,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	Arg             string                 `protobuf:"bytes,6,opt,name=arg,proto3" json:"arg,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	MaxRetry        int32                  `protobuf:"varint,8,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`
	RetryCount      int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Priority        int32                  `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`
	TenantId        string                 `protobuf:"bytes,12,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LogId           string                 `protobuf:"bytes,15,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	LastRunTime     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=last_run_time,json=lastRunTime,proto3" json:"last_run_time,omitempty"`
	LastRunEndTime  *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=last_run_end_time,json=lastRunEndTime,proto3" json:"last_run_end_time,omitempty"`
	LastRunDuration int64                  `protobuf:"varint,18,opt,name=last_run_duration,json=lastRunDuration,proto3" json:"last_run_duration,omitempty"`
	LastResult      string                 `protobuf:"bytes,19,opt,name=last_result,json=lastResult,proto3" json:"last_result,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskItem) Reset() {
	*x = TaskItem{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskItem) ProtoMessage() {}

func (x *TaskItem) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskItem.ProtoReflect.Descriptor instead.
func (*TaskItem) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{1}
}

func (x *TaskItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskItem) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskItem) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *TaskItem) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TaskItem) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *TaskItem) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *TaskItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskItem) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *TaskItem) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *TaskItem) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskItem) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskItem) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TaskItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TaskItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TaskItem) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *TaskItem) GetLastRunTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunTime
	}
	return nil
}

func (x *TaskItem) GetLastRunEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunEndTime
	}
	return nil
}

func (x *TaskItem) GetLastRunDuration() int64 {
	if x != nil {
		return x.LastRunDuration
	}
	return 0
}

func (x *TaskItem) GetLastResult() string {
	if x != nil {
		return x.LastResult
	}
	return ""
}

type SubmitTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	TaskName      string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MethodName    string                 `protobuf:"bytes,4,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	Arg           string                 `protobuf:"bytes,5,opt,name=arg,proto3" json:"arg,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	TenantId      string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	MaxRetry      int32                  `protobuf:"varint,8,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskReq) Reset() {
	*x = SubmitTaskReq{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskReq) ProtoMessage() {}

func (x *SubmitTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskReq.ProtoReflect.Descriptor instead.
func (*SubmitTaskReq) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitTaskReq) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *SubmitTaskReq) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *SubmitTaskReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SubmitTaskReq) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *SubmitTaskReq) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *SubmitTaskReq) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitTaskReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SubmitTaskReq) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

type SubmitTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResp) Reset() {
	*x = SubmitTaskResp{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResp) ProtoMessage() {}

func (x *SubmitTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResp.ProtoReflect.Descriptor instead.
func (*SubmitTaskResp) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitTaskResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskReq) Reset() {
	*x = GetTaskReq{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReq) ProtoMessage() {}

func (x *GetTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReq.ProtoReflect.Descriptor instead.
func (*GetTaskReq) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TaskName      string                 `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page          int64                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TaskStatuses  []string               `protobuf:"bytes,7,rep,name=task_statuses,json=taskStatuses,proto3" json:"task_statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksReq) Reset() {
	*x = ListTasksReq{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksReq) ProtoMessage() {}

func (x *ListTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksReq.ProtoReflect.Descriptor instead.
func (*ListTasksReq) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksReq) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *ListTasksReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTasksReq) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *ListTasksReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListTasksReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksReq) GetTaskStatuses() []string {
	if x != nil {
		return x.TaskStatuses
	}
	return nil
}

type ListTasksResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskItem            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResp) Reset() {
	*x = ListTasksResp{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResp) ProtoMessage() {}

func (x *ListTasksResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResp.ProtoReflect.Descriptor instead.
func (*ListTasksResp) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksResp) GetTasks() []*TaskItem {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RetryTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskReq) Reset() {
	*x = RetryTaskReq{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskReq) ProtoMessage() {}

func (x *RetryTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskReq.ProtoReflect.Descriptor instead.
func (*RetryTaskReq) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{7}
}

func (x *RetryTaskReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CancelTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskReq) Reset() {
	*x = CancelTaskReq{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskReq) ProtoMessage() {}

func (x *CancelTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskReq.ProtoReflect.Descriptor instead.
func (*CancelTaskReq) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTaskReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TaskRecordItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskName      string                 `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	WorkerId      string                 `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LogId         string                 `protobuf:"bytes,9,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Result        string                 `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRecordItem) Reset() {
	*x = TaskRecordItem{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRecordItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRecordItem) ProtoMessage() {}

func (x *TaskRecordItem) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRecordItem.ProtoReflect.Descriptor instead.
func (*TaskRecordItem) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{9}
}

func (x *TaskRecordItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskRecordItem) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskRecordItem) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskRecordItem) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskRecordItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskRecordItem) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskRecordItem) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TaskRecordItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TaskRecordItem) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *TaskRecordItem) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ListRecordsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsReq) Reset() {
	*x = ListRecordsReq{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsReq) ProtoMessage() {}

func (x *ListRecordsReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsReq.ProtoReflect.Descriptor instead.
func (*ListRecordsReq) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ListRecordsReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ListRecordsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRecordsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRecordsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRecordsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*TaskRecordItem      `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResp) Reset() {
	*x = ListRecordsResp{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResp) ProtoMessage() {}

func (x *ListRecordsResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResp.ProtoReflect.Descriptor instead.
func (*ListRecordsResp) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ListRecordsResp) GetRecords() []*TaskRecordItem {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListRecordsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SchedulerInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Theme          string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	IsRunning      bool                   `protobuf:"varint,2,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	WorkerCount    int32                  `protobuf:"varint,3,opt,name=worker_count,json=workerCount,proto3" json:"worker_count,omitempty"`
	QueueDepth     int64                  `protobuf:"varint,4,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	SuccessTotal   int64                  `protobuf:"varint,5,opt,name=success_total,json=successTotal,proto3" json:"success_total,omitempty"`
	FailedTotal    int64                  `protobuf:"varint,6,opt,name=failed_total,json=failedTotal,proto3" json:"failed_total,omitempty"`
	StartedAt      string                 `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Scans          int64                  `protobuf:"varint,8,opt,name=scans,proto3" json:"scans,omitempty"`
	PushTasks      int64                  `protobuf:"varint,9,opt,name=push_tasks,json=pushTasks,proto3" json:"push_tasks,omitempty"`
	PullTasks      int64                  `protobuf:"varint,10,opt,name=pull_tasks,json=pullTasks,proto3" json:"pull_tasks,omitempty"`
	ExecTasks      int64                  `protobuf:"varint,11,opt,name=exec_tasks,json=execTasks,proto3" json:"exec_tasks,omitempty"`
	ExecSuccess    int64                  `protobuf:"varint,12,opt,name=exec_success,json=execSuccess,proto3" json:"exec_success,omitempty"`
	ExecFails      int64                  `protobuf:"varint,13,opt,name=exec_fails,json=execFails,proto3" json:"exec_fails,omitempty"`
	RunningWorkers int32                  `protobuf:"varint,14,opt,name=running_workers,json=runningWorkers,proto3" json:"running_workers,omitempty"`
	AllWorkers     int32                  `protobuf:"varint,15,opt,name=all_workers,json=allWorkers,proto3" json:"all_workers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchedulerInfo) Reset() {
	*x = SchedulerInfo{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerInfo) ProtoMessage() {}

func (x *SchedulerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerInfo.ProtoReflect.Descriptor instead.
func (*SchedulerInfo) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{12}
}

func (x *SchedulerInfo) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *SchedulerInfo) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *SchedulerInfo) GetWorkerCount() int32 {
	if x != nil {
		return x.WorkerCount
	}
	return 0
}

func (x *SchedulerInfo) GetQueueDepth() int64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *SchedulerInfo) GetSuccessTotal() int64 {
	if x != nil {
		return x.SuccessTotal
	}
	return 0
}

func (x *SchedulerInfo) GetFailedTotal() int64 {
	if x != nil {
		return x.FailedTotal
	}
	return 0
}

func (x *SchedulerInfo) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *SchedulerInfo) GetScans() int64 {
	if x != nil {
		return x.Scans
	}
	return 0
}

func (x *SchedulerInfo) GetPushTasks() int64 {
	if x != nil {
		return x.PushTasks
	}
	return 0
}

func (x *SchedulerInfo) GetPullTasks() int64 {
	if x != nil {
		return x.PullTasks
	}
	return 0
}

func (x *SchedulerInfo) GetExecTasks() int64 {
	if x != nil {
		return x.ExecTasks
	}
	return 0
}

func (x *SchedulerInfo) GetExecSuccess() int64 {
	if x != nil {
		return x.ExecSuccess
	}
	return 0
}

func (x *SchedulerInfo) GetExecFails() int64 {
	if x != nil {
		return x.ExecFails
	}
	return 0
}

func (x *SchedulerInfo) GetRunningWorkers() int32 {
	if x != nil {
		return x.RunningWorkers
	}
	return 0
}

func (x *SchedulerInfo) GetAllWorkers() int32 {
	if x != nil {
		return x.AllWorkers
	}
	return 0
}

type ListSchedulersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedulers    []*SchedulerInfo       `protobuf:"bytes,1,rep,name=schedulers,proto3" json:"schedulers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulersResp) Reset() {
	*x = ListSchedulersResp{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulersResp) ProtoMessage() {}

func (x *ListSchedulersResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulersResp.ProtoReflect.Descriptor instead.
func (*ListSchedulersResp) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{13}
}

func (x *ListSchedulersResp) GetSchedulers() []*SchedulerInfo {
	if x != nil {
		return x.Schedulers
	}
	return nil
}

type GetSchedulerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchedulerReq) Reset() {
	*x = GetSchedulerReq{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulerReq) ProtoMessage() {}

func (x *GetSchedulerReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulerReq.ProtoReflect.Descriptor instead.
func (*GetSchedulerReq) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{14}
}

func (x *GetSchedulerReq) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

type StartSchedulerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	WorkerCount   int32                  `protobuf:"varint,2,opt,name=worker_count,json=workerCount,proto3" json:"worker_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSchedulerReq) Reset() {
	*x = StartSchedulerReq{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSchedulerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSchedulerReq) ProtoMessage() {}

func (x *StartSchedulerReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSchedulerReq.ProtoReflect.Descriptor instead.
func (*StartSchedulerReq) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{15}
}

func (x *StartSchedulerReq) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *StartSchedulerReq) GetWorkerCount() int32 {
	if x != nil {
		return x.WorkerCount
	}
	return 0
}

type StopSchedulerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSchedulerReq) Reset() {
	*x = StopSchedulerReq{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSchedulerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSchedulerReq) ProtoMessage() {}

func (x *StopSchedulerReq) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSchedulerReq.ProtoReflect.Descriptor instead.
func (*StopSchedulerReq) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{16}
}

func (x *StopSchedulerReq) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

type TaskStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPending  int64                  `protobuf:"varint,1,opt,name=total_pending,json=totalPending,proto3" json:"total_pending,omitempty"`
	TotalRunning  int64                  `protobuf:"varint,2,opt,name=total_running,json=totalRunning,proto3" json:"total_running,omitempty"`
	TotalSuccess  int64                  `protobuf:"varint,3,opt,name=total_success,json=totalSuccess,proto3" json:"total_success,omitempty"`
	TotalFailed   int64                  `protobuf:"varint,4,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatsResp) Reset() {
	*x = TaskStatsResp{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatsResp) ProtoMessage() {}

func (x *TaskStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatsResp.ProtoReflect.Descriptor instead.
func (*TaskStatsResp) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{17}
}

func (x *TaskStatsResp) GetTotalPending() int64 {
	if x != nil {
		return x.TotalPending
	}
	return 0
}

func (x *TaskStatsResp) GetTotalRunning() int64 {
	if x != nil {
		return x.TotalRunning
	}
	return 0
}

func (x *TaskStatsResp) GetTotalSuccess() int64 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *TaskStatsResp) GetTotalFailed() int64 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

type MetricItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricItem) Reset() {
	*x = MetricItem{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricItem) ProtoMessage() {}

func (x *MetricItem) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricItem.ProtoReflect.Descriptor instead.
func (*MetricItem) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{18}
}

func (x *MetricItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricItem) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AllMetricsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*MetricItem          `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllMetricsResp) Reset() {
	*x = AllMetricsResp{}
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllMetricsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllMetricsResp) ProtoMessage() {}

func (x *AllMetricsResp) ProtoReflect() protoreflect.Message {
	mi := &file_components_asynctask_pb_async_task_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllMetricsResp.ProtoReflect.Descriptor instead.
func (*AllMetricsResp) Descriptor() ([]byte, []int) {
	return file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP(), []int{19}
}

func (x *AllMetricsResp) GetMetrics() []*MetricItem {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_components_asynctask_pb_async_task_admin_proto protoreflect.FileDescriptor

const file_components_asynctask_pb_async_task_admin_proto_rawDesc = "" +
	"\n" +
	".components/asynctask/pb/async_task_admin.proto\x12\fasynctask.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\xb8\x05\n" +
	"\bTaskItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x12\x14\n" +
	"\x05theme\x18\x03 \x01(\tR\x05theme\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vmethod_name\x18\x05 \x01(\tR\n" +
	"methodName\x12\x10\n" +
	"\x03arg\x18\x06 \x01(\tR\x03arg\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1b\n" +
	"\tmax_retry\x18\b \x01(\x05R\bmaxRetry\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x12\x1a\n" +
	"\bpriority\x18\v \x01(\x05R\bpriority\x12\x1b\n" +
	"\ttenant_id\x18\f \x01(\tR\btenantId\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x15\n" +
	"\x06log_id\x18\x0f \x01(\tR\x05logId\x12>\n" +
	"\rlast_run_time\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vlastRunTime\x12E\n" +
	"\x11last_run_end_time\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastRunEndTime\x12*\n" +
	"\x11last_run_duration\x18\x12 \x01(\x03R\x0flastRunDuration\x12\x1f\n" +
	"\vlast_result\x18\x13 \x01(\tR\n" +
	"lastResult\"\xee\x01\n" +
	"\rSubmitTaskReq\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vmethod_name\x18\x04 \x01(\tR\n" +
	"methodName\x12\x10\n" +
	"\x03arg\x18\x05 \x01(\tR\x03arg\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\x12\x1b\n" +
	"\tmax_retry\x18\b \x01(\x05R\bmaxRetry\" \n" +
	"\x0eSubmitTaskResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1c\n" +
	"\n" +
	"GetTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xcc\x01\n" +
	"\fListTasksReq\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\ttask_name\x18\x03 \x01(\tR\btaskName\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x03R\bpageSize\x12#\n" +
	"\rtask_statuses\x18\a \x03(\tR\ftaskStatuses\"S\n" +
	"\rListTasksResp\x12,\n" +
	"\x05tasks\x18\x01 \x03(\v2\x16.asynctask.v1.TaskItemR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x1e\n" +
	"\fRetryTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1f\n" +
	"\rCancelTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xbb\x02\n" +
	"\x0eTaskRecordItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x1b\n" +
	"\ttask_name\x18\x03 \x01(\tR\btaskName\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x15\n" +
	"\x06log_id\x18\t \x01(\tR\x05logId\x12\x16\n" +
	"\x06result\x18\n" +
	" \x01(\tR\x06result\"r\n" +
	"\x0eListRecordsReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"_\n" +
	"\x0fListRecordsResp\x126\n" +
	"\arecords\x18\x01 \x03(\v2\x1c.asynctask.v1.TaskRecordItemR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xee\x03\n" +
	"\rSchedulerInfo\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\x12\x1d\n" +
	"\n" +
	"is_running\x18\x02 \x01(\bR\tisRunning\x12!\n" +
	"\fworker_count\x18\x03 \x01(\x05R\vworkerCount\x12\x1f\n" +
	"\vqueue_depth\x18\x04 \x01(\x03R\n" +
	"queueDepth\x12#\n" +
	"\rsuccess_total\x18\x05 \x01(\x03R\fsuccessTotal\x12!\n" +
	"\ffailed_total\x18\x06 \x01(\x03R\vfailedTotal\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\tR\tstartedAt\x12\x14\n" +
	"\x05scans\x18\b \x01(\x03R\x05scans\x12\x1d\n" +
	"\n" +
	"push_tasks\x18\t \x01(\x03R\tpushTasks\x12\x1d\n" +
	"\n" +
	"pull_tasks\x18\n" +
	" \x01(\x03R\tpullTasks\x12\x1d\n" +
	"\n" +
	"exec_tasks\x18\v \x01(\x03R\texecTasks\x12!\n" +
	"\fexec_success\x18\f \x01(\x03R\vexecSuccess\x12\x1d\n" +
	"\n" +
	"exec_fails\x18\r \x01(\x03R\texecFails\x12'\n" +
	"\x0frunning_workers\x18\x0e \x01(\x05R\x0erunningWorkers\x12\x1f\n" +
	"\vall_workers\x18\x0f \x01(\x05R\n" +
	"allWorkers\"Q\n" +
	"\x12ListSchedulersResp\x12;\n" +
	"\n" +
	"schedulers\x18\x01 \x03(\v2\x1b.asynctask.v1.SchedulerInfoR\n" +
	"schedulers\"'\n" +
	"\x0fGetSchedulerReq\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\"L\n" +
	"\x11StartSchedulerReq\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\x12!\n" +
	"\fworker_count\x18\x02 \x01(\x05R\vworkerCount\"(\n" +
	"\x10StopSchedulerReq\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\"\xa1\x01\n" +
	"\rTaskStatsResp\x12#\n" +
	"\rtotal_pending\x18\x01 \x01(\x03R\ftotalPending\x12#\n" +
	"\rtotal_running\x18\x02 \x01(\x03R\ftotalRunning\x12#\n" +
	"\rtotal_success\x18\x03 \x01(\x03R\ftotalSuccess\x12!\n" +
	"\ftotal_failed\x18\x04 \x01(\x03R\vtotalFailed\"6\n" +
	"\n" +
	"MetricItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"D\n" +
	"\x0eAllMetricsResp\x122\n" +
	"\ametrics\x18\x01 \x03(\v2\x18.asynctask.v1.MetricItemR\ametrics2\xcb\x06\n" +
	"\x0eAsyncTaskAdmin\x12G\n" +
	"\n" +
	"SubmitTask\x12\x1b.asynctask.v1.SubmitTaskReq\x1a\x1c.asynctask.v1.SubmitTaskResp\x12;\n" +
	"\aGetTask\x12\x18.asynctask.v1.GetTaskReq\x1a\x16.asynctask.v1.TaskItem\x12D\n" +
	"\tListTasks\x12\x1a.asynctask.v1.ListTasksReq\x1a\x1b.asynctask.v1.ListTasksResp\x12<\n" +
	"\tRetryTask\x12\x1a.asynctask.v1.RetryTaskReq\x1a\x13.asynctask.v1.Empty\x12>\n" +
	"\n" +
	"CancelTask\x12\x1b.asynctask.v1.CancelTaskReq\x1a\x13.asynctask.v1.Empty\x12J\n" +
	"\vListRecords\x12\x1c.asynctask.v1.ListRecordsReq\x1a\x1d.asynctask.v1.ListRecordsResp\x12<\n" +
	"\bGetStats\x12\x13.asynctask.v1.Empty\x1a\x1b.asynctask.v1.TaskStatsResp\x12G\n" +
	"\x0eListSchedulers\x12\x13.asynctask.v1.Empty\x1a .asynctask.v1.ListSchedulersResp\x12J\n" +
	"\fGetScheduler\x12\x1d.asynctask.v1.GetSchedulerReq\x1a\x1b.asynctask.v1.SchedulerInfo\x12F\n" +
	"\x0eStartScheduler\x12\x1f.asynctask.v1.StartSchedulerReq\x1a\x13.asynctask.v1.Empty\x12D\n" +
	"\rStopScheduler\x12\x1e.asynctask.v1.StopSchedulerReq\x1a\x13.asynctask.v1.Empty\x12B\n" +
	"\rGetAllMetrics\x12\x13.asynctask.v1.Empty\x1a\x1c.asynctask.v1.AllMetricsRespB<Z:github.com/xxzhwl/gaia/components/asynctask/pb;asynctaskpbb\x06proto3"

var (
	file_components_asynctask_pb_async_task_admin_proto_rawDescOnce sync.Once
	file_components_asynctask_pb_async_task_admin_proto_rawDescData []byte
)

func file_components_asynctask_pb_async_task_admin_proto_rawDescGZIP() []byte {
	file_components_asynctask_pb_async_task_admin_proto_rawDescOnce.Do(func() {
		file_components_asynctask_pb_async_task_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_asynctask_pb_async_task_admin_proto_rawDesc), len(file_components_asynctask_pb_async_task_admin_proto_rawDesc)))
	})
	return file_components_asynctask_pb_async_task_admin_proto_rawDescData
}

var file_components_asynctask_pb_async_task_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_components_asynctask_pb_async_task_admin_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: asynctask.v1.Empty
	(*TaskItem)(nil),              // 1: asynctask.v1.TaskItem
	(*SubmitTaskReq)(nil),         // 2: asynctask.v1.SubmitTaskReq
	(*SubmitTaskResp)(nil),        // 3: asynctask.v1.SubmitTaskResp
	(*GetTaskReq)(nil),            // 4: asynctask.v1.GetTaskReq
	(*ListTasksReq)(nil),          // 5: asynctask.v1.ListTasksReq
	(*ListTasksResp)(nil),         // 6: asynctask.v1.ListTasksResp
	(*RetryTaskReq)(nil),          // 7: asynctask.v1.RetryTaskReq
	(*CancelTaskReq)(nil),         // 8: asynctask.v1.CancelTaskReq
	(*TaskRecordItem)(nil),        // 9: asynctask.v1.TaskRecordItem
	(*ListRecordsReq)(nil),        // 10: asynctask.v1.ListRecordsReq
	(*ListRecordsResp)(nil),       // 11: asynctask.v1.ListRecordsResp
	(*SchedulerInfo)(nil),         // 12: asynctask.v1.SchedulerInfo
	(*ListSchedulersResp)(nil),    // 13: asynctask.v1.ListSchedulersResp
	(*GetSchedulerReq)(nil),       // 14: asynctask.v1.GetSchedulerReq
	(*StartSchedulerReq)(nil),     // 15: asynctask.v1.StartSchedulerReq
	(*StopSchedulerReq)(nil),      // 16: asynctask.v1.StopSchedulerReq
	(*TaskStatsResp)(nil),         // 17: asynctask.v1.TaskStatsResp
	(*MetricItem)(nil),            // 18: asynctask.v1.MetricItem
	(*AllMetricsResp)(nil),        // 19: asynctask.v1.AllMetricsResp
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_components_asynctask_pb_async_task_admin_proto_depIdxs = []int32{
	20, // 0: asynctask.v1.TaskItem.created_at:type_name -> google.protobuf.Timestamp
	20, // 1: asynctask.v1.TaskItem.updated_at:type_name -> google.protobuf.Timestamp
	20, // 2: asynctask.v1.TaskItem.last_run_time:type_name -> google.protobuf.Timestamp
	20, // 3: asynctask.v1.TaskItem.last_run_end_time:type_name -> google.protobuf.Timestamp
	1,  // 4: asynctask.v1.ListTasksResp.tasks:type_name -> asynctask.v1.TaskItem
	20, // 5: asynctask.v1.TaskRecordItem.created_at:type_name -> google.protobuf.Timestamp
	9,  // 6: asynctask.v1.ListRecordsResp.records:type_name -> asynctask.v1.TaskRecordItem
	12, // 7: asynctask.v1.ListSchedulersResp.schedulers:type_name -> asynctask.v1.SchedulerInfo
	18, // 8: asynctask.v1.AllMetricsResp.metrics:type_name -> asynctask.v1.MetricItem
	2,  // 9: asynctask.v1.AsyncTaskAdmin.SubmitTask:input_type -> asynctask.v1.SubmitTaskReq
	4,  // 10: asynctask.v1.AsyncTaskAdmin.GetTask:input_type -> asynctask.v1.GetTaskReq
	5,  // 11: asynctask.v1.AsyncTaskAdmin.ListTasks:input_type -> asynctask.v1.ListTasksReq
	7,  // 12: asynctask.v1.AsyncTaskAdmin.RetryTask:input_type -> asynctask.v1.RetryTaskReq
	8,  // 13: asynctask.v1.AsyncTaskAdmin.CancelTask:input_type -> asynctask.v1.CancelTaskReq
	10, // 14: asynctask.v1.AsyncTaskAdmin.ListRecords:input_type -> asynctask.v1.ListRecordsReq
	0,  // 15: asynctask.v1.AsyncTaskAdmin.GetStats:input_type -> asynctask.v1.Empty
	0,  // 16: asynctask.v1.AsyncTaskAdmin.ListSchedulers:input_type -> asynctask.v1.Empty
	14, // 17: asynctask.v1.AsyncTaskAdmin.GetScheduler:input_type -> asynctask.v1.GetSchedulerReq
	15, // 18: asynctask.v1.AsyncTaskAdmin.StartScheduler:input_type -> asynctask.v1.StartSchedulerReq
	16, // 19: asynctask.v1.AsyncTaskAdmin.StopScheduler:input_type -> asynctask.v1.StopSchedulerReq
	0,  // 20: asynctask.v1.AsyncTaskAdmin.GetAllMetrics:input_type -> asynctask.v1.Empty
	3,  // 21: asynctask.v1.AsyncTaskAdmin.SubmitTask:output_type -> asynctask.v1.SubmitTaskResp
	1,  // 22: asynctask.v1.AsyncTaskAdmin.GetTask:output_type -> asynctask.v1.TaskItem
	6,  // 23: asynctask.v1.AsyncTaskAdmin.ListTasks:output_type -> asynctask.v1.ListTasksResp
	0,  // 24: asynctask.v1.AsyncTaskAdmin.RetryTask:output_type -> asynctask.v1.Empty
	0,  // 25: asynctask.v1.AsyncTaskAdmin.CancelTask:output_type -> asynctask.v1.Empty
	11, // 26: asynctask.v1.AsyncTaskAdmin.ListRecords:output_type -> asynctask.v1.ListRecordsResp
	17, // 27: asynctask.v1.AsyncTaskAdmin.GetStats:output_type -> asynctask.v1.TaskStatsResp
	13, // 28: asynctask.v1.AsyncTaskAdmin.ListSchedulers:output_type -> asynctask.v1.ListSchedulersResp
	12, // 29: asynctask.v1.AsyncTaskAdmin.GetScheduler:output_type -> asynctask.v1.SchedulerInfo
	0,  // 30: asynctask.v1.AsyncTaskAdmin.StartScheduler:output_type -> asynctask.v1.Empty
	0,  // 31: asynctask.v1.AsyncTaskAdmin.StopScheduler:output_type -> asynctask.v1.Empty
	19, // 32: asynctask.v1.AsyncTaskAdmin.GetAllMetrics:output_type -> asynctask.v1.AllMetricsResp
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_components_asynctask_pb_async_task_admin_proto_init() }
func file_components_asynctask_pb_async_task_admin_proto_init() {
	if File_components_asynctask_pb_async_task_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_asynctask_pb_async_task_admin_proto_rawDesc), len(file_components_asynctask_pb_async_task_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_components_asynctask_pb_async_task_admin_proto_goTypes,
		DependencyIndexes: file_components_asynctask_pb_async_task_admin_proto_depIdxs,
		MessageInfos:      file_components_asynctask_pb_async_task_admin_proto_msgTypes,
	}.Build()
	File_components_asynctask_pb_async_task_admin_proto = out.File
	file_components_asynctask_pb_async_task_admin_proto_goTypes = nil
	file_components_asynctask_pb_async_task_admin_proto_depIdxs = nil
}
