// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: components/asynctask/pb/async_task_admin.proto

package asynctaskpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AsyncTaskAdmin_SubmitTask_FullMethodName     = "/asynctask.v1.AsyncTaskAdmin/SubmitTask"
	AsyncTaskAdmin_GetTask_FullMethodName        = "/asynctask.v1.AsyncTaskAdmin/GetTask"
	AsyncTaskAdmin_ListTasks_FullMethodName      = "/asynctask.v1.AsyncTaskAdmin/ListTasks"
	AsyncTaskAdmin_RetryTask_FullMethodName      = "/asynctask.v1.AsyncTaskAdmin/RetryTask"
	AsyncTaskAdmin_CancelTask_FullMethodName     = "/asynctask.v1.AsyncTaskAdmin/CancelTask"
	AsyncTaskAdmin_ListRecords_FullMethodName    = "/asynctask.v1.AsyncTaskAdmin/ListRecords"
	AsyncTaskAdmin_GetStats_FullMethodName       = "/asynctask.v1.AsyncTaskAdmin/GetStats"
	AsyncTaskAdmin_ListSchedulers_FullMethodName = "/asynctask.v1.AsyncTaskAdmin/ListSchedulers"
	AsyncTaskAdmin_GetScheduler_FullMethodName   = "/asynctask.v1.AsyncTaskAdmin/GetScheduler"
	AsyncTaskAdmin_StartScheduler_FullMethodName = "/asynctask.v1.AsyncTaskAdmin/StartScheduler"
	AsyncTaskAdmin_StopScheduler_FullMethodName  = "/asynctask.v1.AsyncTaskAdmin/StopScheduler"
	AsyncTaskAdmin_GetAllMetrics_FullMethodName  = "/asynctask.v1.AsyncTaskAdmin/GetAllMetrics"
)

// AsyncTaskAdminClient is the client API for AsyncTaskAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AsyncTaskAdminClient interface {
	SubmitTask(ctx context.Context, in *SubmitTaskReq, opts ...grpc.CallOption) (*SubmitTaskResp, error)
	GetTask(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*TaskItem, error)
	ListTasks(ctx context.Context, in *ListTasksReq, opts ...grpc.CallOption) (*ListTasksResp, error)
	RetryTask(ctx context.Context, in *RetryTaskReq, opts ...grpc.CallOption) (*Empty, error)
	CancelTask(ctx context.Context, in *CancelTaskReq, opts ...grpc.CallOption) (*Empty, error)
	ListRecords(ctx context.Context, in *ListRecordsReq, opts ...grpc.CallOption) (*ListRecordsResp, error)
	GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskStatsResp, error)
	ListSchedulers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSchedulersResp, error)
	GetScheduler(ctx context.Context, in *GetSchedulerReq, opts ...grpc.CallOption) (*SchedulerInfo, error)
	StartScheduler(ctx context.Context, in *StartSchedulerReq, opts ...grpc.CallOption) (*Empty, error)
	StopScheduler(ctx context.Context, in *StopSchedulerReq, opts ...grpc.CallOption) (*Empty, error)
	GetAllMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllMetricsResp, error)
}

type asyncTaskAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewAsyncTaskAdminClient(cc grpc.ClientConnInterface) AsyncTaskAdminClient {
	return &asyncTaskAdminClient{cc}
}

func (c *asyncTaskAdminClient) SubmitTask(ctx context.Context, in *SubmitTaskReq, opts ...grpc.CallOption) (*SubmitTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTaskResp)
	err := c.cc.Invoke(ctx, AsyncTaskAdmin_SubmitTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncTaskAdminClient) GetTask(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*TaskItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskItem)
	err := c.cc.Invoke(ctx, AsyncTaskAdmin_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncTaskAdminClient) ListTasks(ctx context.Context, in *ListTasksReq, opts ...grpc.CallOption) (*ListTasksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResp)
	err := c.cc.Invoke(ctx, AsyncTaskAdmin_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncTaskAdminClient) RetryTask(ctx context.Context, in *RetryTaskReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AsyncTaskAdmin_RetryTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncTaskAdminClient) CancelTask(ctx context.Context, in *CancelTaskReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AsyncTaskAdmin_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncTaskAdminClient) ListRecords(ctx context.Context, in *ListRecordsReq, opts ...grpc.CallOption) (*ListRecordsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecordsResp)
	err := c.cc.Invoke(ctx, AsyncTaskAdmin_ListRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncTaskAdminClient) GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatsResp)
	err := c.cc.Invoke(ctx, AsyncTaskAdmin_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncTaskAdminClient) ListSchedulers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSchedulersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchedulersResp)
	err := c.cc.Invoke(ctx, AsyncTaskAdmin_ListSchedulers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncTaskAdminClient) GetScheduler(ctx context.Context, in *GetSchedulerReq, opts ...grpc.CallOption) (*SchedulerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerInfo)
	err := c.cc.Invoke(ctx, AsyncTaskAdmin_GetScheduler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncTaskAdminClient) StartScheduler(ctx context.Context, in *StartSchedulerReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AsyncTaskAdmin_StartScheduler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncTaskAdminClient) StopScheduler(ctx context.Context, in *StopSchedulerReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AsyncTaskAdmin_StopScheduler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncTaskAdminClient) GetAllMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllMetricsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllMetricsResp)
	err := c.cc.Invoke(ctx, AsyncTaskAdmin_GetAllMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsyncTaskAdminServer is the server API for AsyncTaskAdmin service.
// All implementations must embed UnimplementedAsyncTaskAdminServer
// for forward compatibility.
type AsyncTaskAdminServer interface {
	SubmitTask(context.Context, *SubmitTaskReq) (*SubmitTaskResp, error)
	GetTask(context.Context, *GetTaskReq) (*TaskItem, error)
	ListTasks(context.Context, *ListTasksReq) (*ListTasksResp, error)
	RetryTask(context.Context, *RetryTaskReq) (*Empty, error)
	CancelTask(context.Context, *CancelTaskReq) (*Empty, error)
	ListRecords(context.Context, *ListRecordsReq) (*ListRecordsResp, error)
	GetStats(context.Context, *Empty) (*TaskStatsResp, error)
	ListSchedulers(context.Context, *Empty) (*ListSchedulersResp, error)
	GetScheduler(context.Context, *GetSchedulerReq) (*SchedulerInfo, error)
	StartScheduler(context.Context, *StartSchedulerReq) (*Empty, error)
	StopScheduler(context.Context, *StopSchedulerReq) (*Empty, error)
	GetAllMetrics(context.Context, *Empty) (*AllMetricsResp, error)
	mustEmbedUnimplementedAsyncTaskAdminServer()
}

// UnimplementedAsyncTaskAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAsyncTaskAdminServer struct{}

func (UnimplementedAsyncTaskAdminServer) SubmitTask(context.Context, *SubmitTaskReq) (*SubmitTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTask not implemented")
}
func (UnimplementedAsyncTaskAdminServer) GetTask(context.Context, *GetTaskReq) (*TaskItem, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedAsyncTaskAdminServer) ListTasks(context.Context, *ListTasksReq) (*ListTasksResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedAsyncTaskAdminServer) RetryTask(context.Context, *RetryTaskReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryTask not implemented")
}
func (UnimplementedAsyncTaskAdminServer) CancelTask(context.Context, *CancelTaskReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedAsyncTaskAdminServer) ListRecords(context.Context, *ListRecordsReq) (*ListRecordsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecords not implemented")
}
func (UnimplementedAsyncTaskAdminServer) GetStats(context.Context, *Empty) (*TaskStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedAsyncTaskAdminServer) ListSchedulers(context.Context, *Empty) (*ListSchedulersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchedulers not implemented")
}
func (UnimplementedAsyncTaskAdminServer) GetScheduler(context.Context, *GetSchedulerReq) (*SchedulerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScheduler not implemented")
}
func (UnimplementedAsyncTaskAdminServer) StartScheduler(context.Context, *StartSchedulerReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StartScheduler not implemented")
}
func (UnimplementedAsyncTaskAdminServer) StopScheduler(context.Context, *StopSchedulerReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopScheduler not implemented")
}
func (UnimplementedAsyncTaskAdminServer) GetAllMetrics(context.Context, *Empty) (*AllMetricsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllMetrics not implemented")
}
func (UnimplementedAsyncTaskAdminServer) mustEmbedUnimplementedAsyncTaskAdminServer() {}
func (UnimplementedAsyncTaskAdminServer) testEmbeddedByValue()                        {}

// UnsafeAsyncTaskAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsyncTaskAdminServer will
// result in compilation errors.
type UnsafeAsyncTaskAdminServer interface {
	mustEmbedUnimplementedAsyncTaskAdminServer()
}

func RegisterAsyncTaskAdminServer(s grpc.ServiceRegistrar, srv AsyncTaskAdminServer) {
	// If the following call panics, it indicates UnimplementedAsyncTaskAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AsyncTaskAdmin_ServiceDesc, srv)
}

func _AsyncTaskAdmin_SubmitTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncTaskAdminServer).SubmitTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncTaskAdmin_SubmitTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncTaskAdminServer).SubmitTask(ctx, req.(*SubmitTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncTaskAdmin_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncTaskAdminServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncTaskAdmin_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncTaskAdminServer).GetTask(ctx, req.(*GetTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncTaskAdmin_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncTaskAdminServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncTaskAdmin_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncTaskAdminServer).ListTasks(ctx, req.(*ListTasksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncTaskAdmin_RetryTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncTaskAdminServer).RetryTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncTaskAdmin_RetryTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncTaskAdminServer).RetryTask(ctx, req.(*RetryTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncTaskAdmin_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncTaskAdminServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncTaskAdmin_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncTaskAdminServer).CancelTask(ctx, req.(*CancelTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncTaskAdmin_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncTaskAdminServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncTaskAdmin_ListRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncTaskAdminServer).ListRecords(ctx, req.(*ListRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncTaskAdmin_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncTaskAdminServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncTaskAdmin_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncTaskAdminServer).GetStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncTaskAdmin_ListSchedulers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncTaskAdminServer).ListSchedulers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncTaskAdmin_ListSchedulers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncTaskAdminServer).ListSchedulers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncTaskAdmin_GetScheduler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchedulerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncTaskAdminServer).GetScheduler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncTaskAdmin_GetScheduler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncTaskAdminServer).GetScheduler(ctx, req.(*GetSchedulerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncTaskAdmin_StartScheduler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSchedulerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncTaskAdminServer).StartScheduler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncTaskAdmin_StartScheduler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncTaskAdminServer).StartScheduler(ctx, req.(*StartSchedulerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncTaskAdmin_StopScheduler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSchedulerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncTaskAdminServer).StopScheduler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncTaskAdmin_StopScheduler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncTaskAdminServer).StopScheduler(ctx, req.(*StopSchedulerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncTaskAdmin_GetAllMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncTaskAdminServer).GetAllMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncTaskAdmin_GetAllMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncTaskAdminServer).GetAllMetrics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AsyncTaskAdmin_ServiceDesc is the grpc.ServiceDesc for AsyncTaskAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AsyncTaskAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asynctask.v1.AsyncTaskAdmin",
	HandlerType: (*AsyncTaskAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTask",
			Handler:    _AsyncTaskAdmin_SubmitTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _AsyncTaskAdmin_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _AsyncTaskAdmin_ListTasks_Handler,
		},
		{
			MethodName: "RetryTask",
			Handler:    _AsyncTaskAdmin_RetryTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _AsyncTaskAdmin_CancelTask_Handler,
		},
		{
			MethodName: "ListRecords",
			Handler:    _AsyncTaskAdmin_ListRecords_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _AsyncTaskAdmin_GetStats_Handler,
		},
		{
			MethodName: "ListSchedulers",
			Handler:    _AsyncTaskAdmin_ListSchedulers_Handler,
		},
		{
			MethodName: "GetScheduler",
			Handler:    _AsyncTaskAdmin_GetScheduler_Handler,
		},
		{
			MethodName: "StartScheduler",
			Handler:    _AsyncTaskAdmin_StartScheduler_Handler,
		},
		{
			MethodName: "StopScheduler",
			Handler:    _AsyncTaskAdmin_StopScheduler_Handler,
		},
		{
			MethodName: "GetAllMetrics",
			Handler:    _AsyncTaskAdmin_GetAllMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "components/asynctask/pb/async_task_admin.proto",
}
